### ISSUE TITLE
add myPersonals to myLife

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1011]
Include myPersonals in my life bar. This fragment will have all personal videos, photos, and inn some cases documents they either upload to tablet, or use tablet to capture..

This list must be saved in realmdb for queries, and It must be searchable like what is found in myLibrary

This list is private, and must not be synced back to planet UNLESS, user decides to select any of his / her personals and clicks upload to server.. (It will then be published to planet with his/ her name as the author)

**Comment by rrijal53** [comment]
@leomaxi  so we need to have feature to capture videos, photos and upload document from this fragment or we are just listing all the contents of tablet here?
