### ISSUE TITLE
remove myDraft from option

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1024]
Remove Draft..
<img width="810" alt="Screenshot 2019-07-29 at 3 20 39 PM" src="https://user-images.githubusercontent.com/2836302/62060812-60d2dd00-b215-11e9-8643-36c44b82729b.png">

**Comment by rrijal53** [comment]
@leomaxi  i think we should change the text to upload resource instead of removing . So user can upload the files from their file manager.
