### ISSUE TITLE
Adding a picture through Camera

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/myplanet#1041]
After taking the picture and while giving details, even after checking in the subjects, the toast message appears asking for "subject is required"

![issue_subject](https://user-images.githubusercontent.com/14145400/62383826-be6d6f00-b51e-11e9-81f6-0f4dd90ec413.png)

**Comment by rrijal53** [comment]
@jeevast it is working , need further testing
![Screenshot_1564930228](https://user-images.githubusercontent.com/9145217/62425140-6a69b280-b6f7-11e9-882b-23571d566d15.png)

**Comment by jeevast** [comment]
@rrijal53 alright.

**Comment by rrijal53** [comment]
Not found the issue, closing for now, will reopen if required.
