### ISSUE TITLE
inconsistency with Button UX

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1049]
Button UX size and Look inconsistency 
<img width="827" alt="Screenshot 2019-08-06 at 6 38 32 PM" src="https://user-images.githubusercontent.com/2836302/62567032-df64f580-b879-11e9-8a96-0ef1b90521e5.png">

**Comment by raisinman99** [comment]
Is it ok if I work on this? I added a radius to the buttons and it seems I missed this one.

**Comment by ChiragAwale** [comment]
@raisinman99 Yes go ahead

**Comment by leomaxi** [comment]
Fixed
