### ISSUE TITLE
Team detail crash

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1073]
<img width="1101" alt="Screen Shot 2019-08-18 at 21 03 19" src="https://user-images.githubusercontent.com/9145217/63226616-a3c41700-c1fb-11e9-83e0-06912587dd0c.png">

**Comment by ChiragAwale** [comment]
I don't seem to be able to recreate the issue

**Comment by rrijal53** [comment]
@ChiragAwale i m changing whole team detail fragment in https://github.com/open-learning-exchange/myplanet/pull/1074  so we dont have to work on this issue.

**Comment by ChiragAwale** [comment]
@rrijal53 gotcha

**Comment by rrijal53** [comment]
fixed in recent PR
