### ISSUE TITLE
myPersonal : resource are not uploading to nations

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1079]

**Comment by rrijal53** [comment]
@leomaxi i tried to upload to dev and it is uploaded.
<img width="838" alt="Screen Shot 2019-08-25 at 22 04 03" src="https://user-images.githubusercontent.com/9145217/63652814-50fed800-c784-11e9-9bab-fb84ef80c917.png">

**Comment by leomaxi** [comment]
Awesome
