### ISSUE TITLE
Reference fragment is opened when clicking myhealth,, mymessages etc

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1082]
![Screenshot_1566575841](https://user-images.githubusercontent.com/9145217/63606051-f7b17000-c5ee-11e9-8e3a-07b1face8353.png)
![Screenshot_1566575842](https://user-images.githubusercontent.com/9145217/63606058-f97b3380-c5ee-11e9-941e-0aa49c43623e.png)

**Comment by ChiragAwale** [comment]
<img width="434" alt="Screen Shot 2019-08-24 at 5 51 29 PM" src="https://user-images.githubusercontent.com/19680263/63643520-d0fb4400-c697-11e9-82a5-333cdceb0559.png">
My health opening when i click on My health

**Comment by ChiragAwale** [comment]
When clicking on myMessages

**Comment by rrijal53** [comment]
@ChiragAwale  i fixed that in recent PR.

**Comment by ChiragAwale** [comment]
@rrijal53 oh gotcha :D
