### ISSUE TITLE
Dynamic button in team

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/myplanet#1084]
In teams after giving request, change the button dynamically to "cancel request", so that even if it's accidentally clicked it can be revoked.

![Screenshot_20190823-123437](https://user-images.githubusercontent.com/14145400/63608446-0c681680-c5a3-11e9-8fe3-f67679021308.png)

**Comment by ChiragAwale** [comment]
That is a good idea.

**Comment by leomaxi** [comment]
Will result in  conflict  especially  when the request is synced to the planet and  it is cancelled offline  on  another tablet
