### ISSUE TITLE
add myplanet version to crash log

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#1095]

**Comment by leomaxi** [comment]
`{"_id":"01c5c45f6c15a5601c22777ef60024dd","_rev":"1-0f7a61276be6a6b948bc34612e708d94","type":"crash","error":"null--------- Stack trace ---------\n\njava.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.ole.planet.myplanet.model.RealmTag.getName()' on a null object reference\n\n    org.ole.planet.myplanet.ui.course.AdapterCourses.showChip(AdapterCourses.java:144)\n    org.ole.planet.myplanet.ui.course.AdapterCourses.showTags(AdapterCourses.java:139)\n    org.ole.planet.myplanet.ui.course.AdapterCourses.displayTagCloud(AdapterCourses.java:133)\n    org.ole.planet.myplanet.ui.course.AdapterCourses.onBindViewHolder(AdapterCourses.java:108)\n    android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)\n    android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)\n    android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)\n    android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)\n    android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)\n    android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)\n    android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)\n    android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)\n    android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)\n    android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)\n    android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)\n    android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)\n    android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)\n    android.widget.FrameLayout.onLayout(FrameLayout.java:321)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)\n    android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)\n    android.widget.LinearLayout.onLayout(LinearLayout.java:1735)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)\n    android.widget.FrameLayout.onLayout(FrameLayout.java:321)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)\n    android.widget.FrameLayout.onLayout(FrameLayout.java:321)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)\n    android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)\n    android.widget.LinearLayout.onLayout(LinearLayout.java:1735)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)\n    android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)\n    android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)\n    android.widget.FrameLayout.onLayout(FrameLayout.java:321)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)\n    android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)\n    android.widget.LinearLayout.onLayout(LinearLayout.java:1735)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)\n    android.widget.FrameLayout.onLayout(FrameLayout.java:321)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)\n    android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)\n    android.widget.LinearLayout.onLayout(LinearLayout.java:1735)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)\n    android.widget.FrameLayout.onLayout(FrameLayout.java:321)\n    com.android.internal.policy.DecorView.onLayout(DecorView.java:751)\n    android.view.View.layout(View.java:17838)\n    android.view.ViewGroup.layout(ViewGroup.java:5754)\n    android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2711)\n    android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)\n    android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)\n    android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)\n    android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)\n    android.view.Choreographer.doCallbacks(Choreographer.java:709)\n    android.view.Choreographer.doFrame(Choreographer.java:644)\n    android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)\n    android.os.Handler.handleCallback(Handler.java:836)\n    android.os.Handler.dispatchMessage(Handler.java:103)\n    android.os.Looper.loop(Looper.java:203)\n    android.app.ActivityThread.main(ActivityThread.java:6251)\n    java.lang.reflect.Method.invoke(Native Method)\n    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)\n    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)\n-------------------------------\n\n--------- Cause ---------\n\n-------------------------------\n\n","page":"","time":"1566041444966","createdOn":"peacebuilder5","parentCode":"somalia"}`
