### ISSUE TITLE
after syncing app crashed when try to login

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1100]
after syncing app crashed when try to login till reopened...
<img width="868" alt="Screenshot 2019-08-29 at 5 16 54 PM" src="https://user-images.githubusercontent.com/2836302/63961758-05e50d80-ca81-11e9-8eb7-e044f27763b3.png">

**Comment by ChiragAwale** [comment]
@leomaxi Did the error reoccur?

**Comment by rrijal53** [comment]
fixed
