### ISSUE TITLE
app goes unresponsive for wrong password

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/myplanet#1108]
The application goes unresponsive when the user enters the wrong password, better to pop up a new dialog box asking them to reenter the password.

![login_issue](https://user-images.githubusercontent.com/14145400/64036402-1ea50000-cb21-11e9-8d21-4a1c943d44aa.png)

**Comment by ChiragAwale** [comment]
Is it recurring?

**Comment by jeevast** [comment]
As far as I checked, yes it is.

**Comment by rrijal53** [comment]
@jeevast  this is fixed already are you getting this error in new version also??

**Comment by rrijal53** [comment]
not seeing this issue in new version , closing for now.
