### ISSUE TITLE
app crashes on switching from bell dashboard theme

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/myplanet#1109]
As it's no longer offered, it's better to take this functionality off, cause the application would terribly crash if someone accidentally switches this(bell dashboard theme) toggle button.

![bell_dashboard](https://user-images.githubusercontent.com/14145400/64037366-675db880-cb23-11e9-849f-9eef2b29e0b9.png)

**Comment by ChiragAwale** [comment]
Yes we should disable it for now.
