### ISSUE TITLE
Dashboard load error

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1114]
<img width="836" alt="Screenshot 2019-09-02 at 2 14 20 PM" src="https://user-images.githubusercontent.com/2836302/64120572-0edd2400-cd8c-11e9-8d79-b5bc7f8ffed5.png">

**Comment by rrijal53** [comment]
@leomaxi  fixed in existing PR. https://github.com/open-learning-exchange/myplanet/pull/1113

**Comment by rrijal53** [comment]
done
