### ISSUE TITLE
Encrypt / Decrypt data in AES 256 for myHealth Data

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1128]

**Comment by rrijal53** [comment]
@leomaxi  this one is only for private resources isn't it ?

**Comment by leomaxi** [comment]
No. For myHealth date in the database

**Comment by leomaxi** [comment]
https://howtodoinjava.com/security/aes-256-encryption-decryption/

**Comment by leomaxi** [comment]
Planet sample https://github.com/open-learning-exchange/planet/pull/4626

**Comment by leomaxi** [comment]
`Samples`

https://github.com/ricmoo/aes-js
https://www.devglan.com/online-tools/aes-encryption-decryption
