### ISSUE TITLE
Enterprise tab bar titles

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1153]
Enterprise tab bar titles must be same as planet.. eg. Discussion must be messages in enterprise. 
<img width="1249" alt="Screenshot 2019-09-11 at 7 14 12 PM" src="https://user-images.githubusercontent.com/2836302/64727805-3721fc80-d4c9-11e9-9201-fcfcad2267d3.png">

**Comment by ChiragAwale** [comment]
Completed
