### ISSUE TITLE
Show name in myHealth 

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1160]
Userid is shown in myHealth list we need to show name their
<img width="536" alt="Screen Shot 2019-09-13 at 21 37 06" src="https://user-images.githubusercontent.com/9145217/64876399-c0266880-d66e-11e9-8fb4-1b0e23f52505.png">

**Comment by leomaxi** [comment]
Fixed in https://github.com/open-learning-exchange/myplanet/pull/1215
