### ISSUE TITLE
Enterprise shows double on team bar

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1163]
<img width="763" alt="Screenshot 2019-09-13 at 4 22 45 PM" src="https://user-images.githubusercontent.com/2836302/64878425-09f95980-d643-11e9-9fdc-d74221492506.png">

**Comment by rrijal53** [comment]
@leomaxi  fixed in recent PR i think , is this still the same?

**Comment by leomaxi** [comment]
Fixed
