### ISSUE TITLE
Task : format date (Deadline)

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1182]
Deadline is in timestamp, Make it human readable.
![Screenshot_1568992931](https://user-images.githubusercontent.com/9145217/65338799-ae9f0c80-dbea-11e9-901c-f134df47488b.png)

**Comment by ChiragAwale** [comment]
![Screen Shot 2019-09-24 at 8 03 36 PM](https://user-images.githubusercontent.com/19680263/65560982-6c394080-df06-11e9-8fa3-79632cad150e.png)
I am getting this error and crash
