### ISSUE TITLE
Bell dashboard : Wifi switch is missing 

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1184]
We dont have wifi switch in bell dashboard . It is only in DashboardFragment

<img width="315" alt="Screen Shot 2019-09-20 at 21 11 17" src="https://user-images.githubusercontent.com/9145217/65339169-68967880-dbeb-11e9-8b1f-efa63443a003.png">

**Comment by avin-sharma** [comment]
Is this issue still active?

**Comment by mattscodeans** [comment]
No I don't think so. Not sure how to implement this with the current UI.

**Comment by leomaxi** [comment]
Depreciated function
