### ISSUE TITLE
Add feedback button in team and enterprise list

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1188]
<img width="470" alt="Screen Shot 2019-09-20 at 21 30 28" src="https://user-images.githubusercontent.com/9145217/65340424-e65b8380-dbed-11e9-9616-92699c9c08d5.png">

**Comment by ChiragAwale** [comment]
@rrijal53 I was looking at the difference in database entries, I found state and item new there. I get what state is, but what is "item"
![image](https://user-images.githubusercontent.com/19680263/65826419-484d6600-e24a-11e9-802e-8ccb5aa383d3.png)

**Comment by ChiragAwale** [comment]
@rrijal53 Got it nvm
