### ISSUE TITLE
Change Ent finance calendar

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1200]
`Look like this`

https://github.com/savvisingh/DateRangePicker?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=7677

<img width="724" alt="Screenshot 2019-09-25 at 9 17 13 AM" src="https://raw.githubusercontent.com/savvisingh/DateRangePicker/master/art/device-2019-05-22-131815.png">

**Comment by rrijal53** [comment]
@leomaxi found one good library https://github.com/tobiasschuerg/android-week-view 

tying to implement.

**Comment by leomaxi** [comment]
How far with it implementation ?

**Comment by rrijal53** [comment]
done
