### ISSUE TITLE
Bring back feedback icon on-top of myPlanet

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1221]
Show feedback icon on top
Members must be able send feedback by clicking this button and the feedback will be linked to the page the member has in view ; just as Planet. 

`Feedback on enterprises is redundant if the icon is shown`

<img width="767" alt="Screenshot 2019-10-04 at 7 21 02 PM" src="https://user-images.githubusercontent.com/2836302/66239315-15dbb700-e6e9-11e9-80c8-4707c8f8cf12.png">

**Comment by ChiragAwale** [comment]
@leomaxi The feedback on enterprise list is item-specific though

**Comment by leomaxi** [comment]
We are to remove that feedback button from Enterprises

**Comment by anikx7** [comment]
@leomaxi Does it mean the feedback icon will be shown all the time in the top toolbar like planet? 
![feedback issue](https://user-images.githubusercontent.com/26880012/68230645-0d63ee00-ffbf-11e9-9248-dcb4c94b3f6d.JPG)
