### ISSUE TITLE
myHealth table

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1222]
add to  myHealth table (Name, date, temperature, pulse ,Blood pressure, wgt, etc as shown in planet) -- Filter by date / duration

**Comment by ChiragAwale** [comment]
@leomaxi 
<img width="692" alt="Screen Shot 2019-10-14 at 5 12 19 PM" src="https://user-images.githubusercontent.com/19680263/66786394-ca25cc00-eea5-11e9-8d0b-47a7639daa41.png">
I do not think we are storing date here. Should I add it first and then work on the filter?

**Comment by leomaxi** [comment]
'Page must be as follows'
<img width="1645" alt="Screenshot 2019-10-15 at 11 57 40 AM" src="https://user-images.githubusercontent.com/2836302/66830601-5e933b80-ef45-11e9-8d2f-de3735c065e0.png">

**Comment by ChiragAwale** [comment]
@leomaxi Gotcha. So do we ask the examination date or store it automatically as the date entered
