### ISSUE TITLE
Back button not working on vital sign detail page

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/myplanet#1237]
![image](https://user-images.githubusercontent.com/19680263/66786224-479d0c80-eea5-11e9-9e4e-f4cb965f1913.png)
![image](https://user-images.githubusercontent.com/19680263/66786217-39e78700-eea5-11e9-8f19-264d6ee08138.png)

**Comment by rrijal53** [comment]
closing this issue  , as this page doesnot exists in new version.
