### ISSUE TITLE
App crashes in collection

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1242]

**Comment by leomaxi** [comment]
<img width="726" alt="Screenshot 2019-10-16 at 5 32 19 PM" src="https://user-images.githubusercontent.com/2836302/66943565-f757b300-f03a-11e9-93a9-f524641a81cc.png">

**Comment by leomaxi** [comment]
<img width="718" alt="Screenshot 2019-10-16 at 5 34 46 PM" src="https://user-images.githubusercontent.com/2836302/66944073-fc693200-f03b-11e9-9d4c-020e029d9e6d.png">
