### ISSUE TITLE
Team Visits not showing on Planet

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1243]
Number # of Team Visits not showing accurately on Planet.. Need to debug it

**Comment by rrijal53** [comment]
It is working in mine.
# My planet
![Screenshot_1571577867](https://user-images.githubusercontent.com/9145217/67160174-b8dd3380-f36d-11e9-9a42-0e5379824761.png)

# Planet before sync
<img width="1103" alt="Screen Shot 2019-10-20 at 19 09 35" src="https://user-images.githubusercontent.com/9145217/67160179-c4c8f580-f36d-11e9-9d9c-0b591554816a.png">

#Planet After Sync
<img width="956" alt="Screen Shot 2019-10-20 at 19 09 51" src="https://user-images.githubusercontent.com/9145217/67160186-cdb9c700-f36d-11e9-81fd-43fa6d26e1ae.png">

**Comment by leomaxi** [comment]
"referring to team"
<img width="764" alt="Screenshot 2019-10-22 at 1 11 49 PM" src="https://user-images.githubusercontent.com/2836302/67289100-93673b80-f4cd-11e9-8c61-31ceb5fd63e2.png">

**Comment by rrijal53** [comment]
@leomaxi  sorry my mistake :D
