### ISSUE TITLE
sync recent resources first before old ones

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1269]
sync recent resources first before old ones

**Comment by rrijal53** [comment]
@leomaxi  i tried sorting by createdDate and upload date but getting this error.

<img width="260" alt="Screen Shot 2019-10-24 at 07 06 07" src="https://user-images.githubusercontent.com/9145217/67504841-ded64100-f6a9-11e9-8f25-45bee378875c.png">

**Comment by leomaxi** [comment]
What error

**Comment by rrijal53** [comment]
@leomaxi  sorry uploaded wrong one.

**Comment by rrijal53** [comment]
@leomaxi  
<img width="911" alt="Screen Shot 2019-10-25 at 20 20 57" src="https://user-images.githubusercontent.com/9145217/67579874-0c33f500-f765-11e9-8820-04afb85b338b.png">

**Comment by leomaxi** [comment]
Will pass it by @paulbert and @lmmrssa today
