### ISSUE TITLE
myHealth - Examination (observation)

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1295]
@leomaxi Will add list of medical conditions to be populated for selection 

<img width="909" alt="Screenshot 2019-10-30 at 5 14 32 PM" src="https://user-images.githubusercontent.com/2836302/67881738-f6de1280-fb38-11e9-85db-0d9672dd62f6.png">

**Comment by leomaxi** [comment]
Cancer 
Cardiovascular disorders 
Cirrhosis of the liver
Diabetes
Diarrhoea diseases 
Ebola
Epilepsy 
Flu
Influenza
Ischaemic heat disease
Malaria, 
Malnutrition
Meningitis 
Neonatal sepsis and infections
HIV/AIDS
Pneumonia 
Stroke
tuberculosis

**Comment by rrijal53** [comment]
done
