### ISSUE TITLE
App crashes when adding examination

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1300]
<img width="1298" alt="Screen Shot 2019-11-01 at 21 01 55" src="https://user-images.githubusercontent.com/9145217/68035094-0bfaa300-fceb-11e9-9a29-77a8d9d14fd6.png">

**Comment by ChiragAwale** [comment]
![image](https://user-images.githubusercontent.com/19680263/68037300-6ec14f80-fc95-11e9-94e2-09fdc34e2be6.png)
