### ISSUE TITLE
Make field titles bold in helpwanted fragment 

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/myplanet#1306]
![image](https://user-images.githubusercontent.com/19680263/68036768-56046a00-fc94-11e9-826e-938faf0ffadc.png)

**Comment by nvrqt03** [comment]
What's the path to get to that screenshot?

**Comment by ChiragAwale** [comment]
In the Mylife part of dashboard scroll until you find Help wanted button

**Comment by nvrqt03** [comment]
Fixed by issue #1355
