### ISSUE TITLE
Empty list text in mySurvey

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/myplanet#1307]
![image](https://user-images.githubusercontent.com/19680263/68036943-a7acf480-fc94-11e9-9057-e777cf991008.png)

**Comment by nvrqt03** [comment]
I'm seeing my surveys listed
![mySurveys](https://user-images.githubusercontent.com/22177989/69084285-8e80a380-0a09-11ea-99ef-075fc2f4c6de.png)

**Comment by ChiragAwale** [comment]
@nvrqt03 We need a text view saying Its empty when no survey is listed. Please check with another account.
