### ISSUE TITLE
Current day & Month remain same in all years

### ISSUE THREAD

**Issue by anikx7** [open-learning-exchange/myplanet#1317]
The current date remains the same whether you go forward or backward. For instance, today is Nov 5, 2019. myCalender highlighted this date. But, when you go forward or backward to a different year, Nov 5 will be always highlighted like Nov 5, 2018, or Nov 5, 2020.

myPlanet Home/ myCalender/ go backward or forward
![calenderIssu](https://user-images.githubusercontent.com/26880012/68229435-e1e00400-ffbc-11e9-8b88-0cd9b9dd23db.JPG)

**Comment by ChiragAwale** [comment]
Good catch. You can work on it.

**Comment by leomaxi** [comment]
Got new calendar for this
