### ISSUE TITLE
survey :  1 / 0 questions or no questions 

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1325]
<img width="928" alt="Screenshot 2019-11-08 at 8 32 43 AM" src="https://user-images.githubusercontent.com/2836302/68461629-8ef78e00-0202-11ea-8fdf-d918a0684ade.png">
<img width="896" alt="Screenshot 2019-11-08 at 8 31 43 AM" src="https://user-images.githubusercontent.com/2836302/68461657-9fa80400-0202-11ea-8910-46186cbbc533.png">

**Comment by rrijal53** [comment]
done
