### ISSUE TITLE
Last sync date and version on planet

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1343]
Last sync date and version doesn't report correctly on planet. Need to debug if there is a possible problem.

**Comment by rrijal53** [comment]
@leomaxi  
Working for me. 
<img width="1384" alt="Screen Shot 2019-11-13 at 20 23 21" src="https://user-images.githubusercontent.com/9145217/68773423-a0ea8e00-0653-11ea-9e63-562141f6d744.png">
