### ISSUE TITLE
Custom device name in settings

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1346]
<img width="925" alt="Screenshot 2019-11-13 at 4 21 16 PM" src="https://user-images.githubusercontent.com/2836302/68782972-22c9bf80-0632-11ea-9e01-4b35b346044b.png">

**Comment by ChiragAwale** [comment]
@leomaxi  where do we set it?

**Comment by leomaxi** [comment]
As explained on our last meeting, it will be in the settings dialogue.

**Comment by ChiragAwale** [comment]
@leomaxi Got it. I will be pushing shortly.
