### ISSUE TITLE
Update number of resource notifications

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/myplanet#1349]
On load when notifications pops up at the bottom, we don't see the resources being updated. For this one, there should be at least 4. 

![connection failed b](https://user-images.githubusercontent.com/22177989/68884822-98d53180-06d9-11ea-9980-26537545a302.png)

**Comment by rrijal53** [comment]
@nvrqt03  it only shows the resources coutn from myLibrary. Not from our library.
