### ISSUE TITLE
Button text add to courses

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/myplanet#1350]
**Button "add to my courses" text is too big for the button.** 

**Path** - Our Courses -> click on course -> button on top right 

![add to my courses button](https://user-images.githubusercontent.com/22177989/68957621-06439980-0790-11ea-9119-251a39ffd369.png)

**Comment by leomaxi** [comment]
Change to Join
<img width="1668" alt="Screenshot 2019-12-04 at 3 36 36 PM" src="https://user-images.githubusercontent.com/2836302/70156624-22aa6600-16ac-11ea-96ff-bff6bf9bc82b.png">

Change to Join Selected
<img width="1674" alt="Screenshot 2019-12-04 at 3 35 50 PM" src="https://user-images.githubusercontent.com/2836302/70156625-22aa6600-16ac-11ea-9d53-30cc45fad2a3.png">

**Comment by leomaxi** [comment]
`Yellow Button`
<img width="1344" alt="Screenshot 2019-12-04 at 4 33 36 PM" src="https://user-images.githubusercontent.com/2836302/70161428-f2ff5c00-16b3-11ea-9ed5-228d6e163b3b.png">

**Comment by nvrqt03** [comment]
I've updated the text, but all of the buttons throughout the app are either blue or grey. We can update the color, but we may need to decide what buttons we want to stay blue, and which ones we want yellow. 

![greyButtons](https://user-images.githubusercontent.com/22177989/70277776-9f0a7b00-1778-11ea-8e88-38d68bdd640e.png)

**Comment by leomaxi** [comment]
Has to be as Planet. All Buttons that are found on Planet and same time found on myPlanet has to be the . same
