### ISSUE TITLE
only prompt to update with condition

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1357]
if `http://address/versions` -> latestapk is equal to `http://address/apkversion` 
<img width="761" alt="Screenshot 2019-11-15 at 5 10 27 PM" src="https://user-images.githubusercontent.com/2836302/68961970-702d6480-07cb-11ea-9f31-c49a81209a41.png">

`Same as`
<img width="564" alt="Screenshot 2019-11-15 at 5 10 43 PM" src="https://user-images.githubusercontent.com/2836302/68961960-6c014700-07cb-11ea-80f4-68024bfc347e.png">

**Comment by lmmrssa** [comment]
currentVersion < localversion -> show local upgrade
currentVersion < maxversion but >= localversion -> hide local and show only internet
currentVersion >= version -> hide upgrade completely
currentVersion < minversion but >= localversion -> show upgrade internet (do not force upgrade)
currentVersion < minversion and < localversion -> force upgrade
