### ISSUE TITLE
Redirected to referenced page when clicked on a survey

### ISSUE THREAD

**Issue by anikx7** [open-learning-exchange/myplanet#1358]
When I clicked on the survey which is not defined, it redirected to reference page.

![survey](https://user-images.githubusercontent.com/26880012/68962386-119bc280-079a-11ea-8824-0b0cedd184b9.JPG)

![survey 2](https://user-images.githubusercontent.com/26880012/68962525-6c351e80-079a-11ea-895d-8208795086dc.JPG)

**Comment by rrijal53** [comment]
@anikx7  This happens when you double click on any view on dashboard activity.
