### ISSUE TITLE
remove survey from top menu  

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1368]
<img width="921" alt="Screenshot 2019-11-20 at 3 17 33 PM" src="https://user-images.githubusercontent.com/2836302/69251544-79db1180-0ba9-11ea-861c-6f449df2bf58.png">

<img width="908" alt="Screenshot 2019-11-20 at 3 17 54 PM" src="https://user-images.githubusercontent.com/2836302/69251486-5fa13380-0ba9-11ea-95e5-3b6e2775361b.png">

**Comment by ChiragAwale** [comment]
@leomaxi Where should we put it now>?

**Comment by rrijal53** [comment]
already done
