### ISSUE TITLE
Floating menu on all fragments -  throughout app

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1369]
<img width="957" alt="Screenshot 2019-11-20 at 3 22 29 PM" src="https://user-images.githubusercontent.com/2836302/69251804-dccca880-0ba9-11ea-8208-ca83f17cf38d.png">
<img width="896" alt="Screenshot 2019-11-20 at 3 22 56 PM" src="https://user-images.githubusercontent.com/2836302/69251810-df2f0280-0ba9-11ea-94d5-a95610c3f62c.png">

**Comment by ChiragAwale** [comment]
@leomaxi what should be the menu options?

**Comment by ChiragAwale** [comment]
done in another pr
