### ISSUE TITLE
reduce space between top menu

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1379]
reduce space between top menu, we can lamp them together, remove `Our` from Courses and Library on top.
<img width="717" alt="Screenshot 2019-11-22 at 8 09 32 PM" src="https://user-images.githubusercontent.com/2836302/69457214-7a6bd780-0d64-11ea-8bc5-9a663c3ebfd4.png">

**Comment by nvrqt03** [comment]
I have removed "Our". the menu bar is scrollable.  do we want to keep that functionality or get rid of it in order to reduce space at top menu?
