### ISSUE TITLE
add photo to news

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1387]
add photo to news message. (Save db as attachment )
<img width="718" alt="Screenshot 2019-11-27 at 11 29 03 AM" src="https://user-images.githubusercontent.com/2836302/69719850-464c3a00-1109-11ea-8c3b-0d0ced796a97.png">
<img width="719" alt="Screenshot 2019-11-27 at 11 28 42 AM" src="https://user-images.githubusercontent.com/2836302/69736728-fbdbb500-112a-11ea-91dc-1cf52cd6dd12.png">

**Comment by ChiragAwale** [comment]
You mean users should be able to upload pics when submitting a news?

**Comment by leomaxi** [comment]
Yes. Only one image per message for the start;

**Comment by ChiragAwale** [comment]
@leomaxi got it

**Comment by ChiragAwale** [comment]
@rrijal53 Everything is done, but the photo is not loading from glide. Would you be able to have a look at it?

**Comment by rrijal53** [comment]
@ChiragAwale  please push the code , i will fix that error.

**Comment by ChiragAwale** [comment]
@rrijal53 okay, sorry about the delay been busy with exams and papers

**Comment by ChiragAwale** [comment]
@rrijal53 Please check add-image-news
