### ISSUE TITLE
Sign in button on the login screen on some devices doesn't look good

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1408]
Sign in button on the login screen on some devices doesn't look good. Space between text and button border is not enough 
<img width="802" alt="Screenshot 2019-12-04 at 9 24 51 AM" src="https://user-images.githubusercontent.com/2836302/70130199-07256800-1678-11ea-9d80-65c254caaa32.png">

**Comment by nvrqt03** [comment]
I believe this has been fixed. Can we close this issue?

10.1 WXGA - 
![10 1 WXGA](https://user-images.githubusercontent.com/22177989/71993595-f929b080-31fc-11ea-9772-6bc434e938b8.png)

Nexus 9
![Nexus 9](https://user-images.githubusercontent.com/22177989/71993627-08106300-31fd-11ea-9ff6-11d8ba4d76c5.png)

Nexus 7
![Nexus 7](https://user-images.githubusercontent.com/22177989/71993643-0e9eda80-31fd-11ea-9a0d-83b983630949.png)

Pixel 2 XL
![Pixel 2](https://user-images.githubusercontent.com/22177989/71993676-1c546000-31fd-11ea-8682-8cb95dbab425.png)

**Comment by leomaxi** [comment]
working now
