### ISSUE TITLE
myHealth Sync Failed

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1419]
<img width="1097" alt="Screenshot 2019-12-05 at 6 58 20 PM" src="https://user-images.githubusercontent.com/2836302/70265158-b99d1e00-1791-11ea-985a-f2b1d3e4ba58.png">

**Comment by rrijal53** [comment]
It is working in mine 
![Screenshot_1575641360](https://user-images.githubusercontent.com/9145217/70328903-40213080-1862-11ea-9ca7-13f8dcd85647.png)

**Comment by leomaxi** [comment]
Works here too. Just that sometimes it doesn't get the data.
