### ISSUE TITLE
markdown images

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1433]
Planet has implemented inserting images into news / messages. It shows as link on myPlanet instead of downloading the photo resources unto tablet and displaying it.

<img width="908" alt="Screenshot 2019-12-10 at 4 53 23 PM" src="https://user-images.githubusercontent.com/2836302/70550602-e96f6b80-1b6d-11ea-9592-46c1ebb20e36.png">

**Comment by rrijal53** [comment]
done in https://github.com/open-learning-exchange/myplanet/pull/1481

**Comment by rrijal53** [comment]
done
