### ISSUE TITLE
save on tablet log

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1440]
- How long myPlanet is used (Log the time the app has been on)
- How long the tablet is on (To measure, how often the tablet is charged / and used )

**Comment by rrijal53** [comment]
<img width="1159" alt="Screen Shot 2019-12-13 at 22 25 47" src="https://user-images.githubusercontent.com/9145217/70816474-aaece180-1df7-11ea-8385-4d744bd84119.png">
