### ISSUE TITLE
Surveys: Final information dialog only for "Record Survey"

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1442]
The final dialog that comes up after the last answer is submitted for a survey should only appear if the survey started with the "Record Survey" button in the list of surveys.

If the survey is started from the "Pending survey" notification or from "mySurvey", then there should not be a dialog at the end of the survey.  If **any** field is filled out it overwrites the user data of the person taking the survey.

![Screenshot_2019-12-12-09-28-46](https://user-images.githubusercontent.com/9203229/70720904-b4c0f880-1cc2-11ea-952c-4b03b6fa4577.png)

**Comment by leomaxi** [comment]
Local survey or community survey?.
