### ISSUE TITLE
Team : request to join my own created team on myPlanet

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1445]
After creating a team on myPlanet, It still shows up request to join the team i just created. This shouldn't be so. 

<img width="911" alt="Screenshot 2019-12-12 at 6 16 42 PM" src="https://user-images.githubusercontent.com/2836302/70737922-8f0c1180-1d0b-11ea-9d7c-60e428000a66.png">

**Comment by anthonyhvo12** [comment]
The same goes for Planet - if a team was created on myPlanet, the "Request to Join" button would also appear on Planet.
