### ISSUE TITLE
Survey/Exam sync: Image documents missing type property

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1448]
After a sync to Planet documents on CouchDB are created in the `submissions` database without a user property.  This breaks the view of all exam and survey submissions within Planet.

![image](https://user-images.githubusercontent.com/9203229/70811971-b2c76a00-1d94-11ea-86e5-d218f834c397.png)

**Comment by leomaxi** [comment]
Why does these submissions have images too. :)

**Comment by paulbert** [comment]
Looks like these are missing a **type** property, which should be set to "photo" in these cases:

![image](https://user-images.githubusercontent.com/9203229/70813916-58300d00-1d98-11ea-9ec2-725bd9c2add7.png)

**Comment by leomaxi** [comment]
Resolved in https://github.com/open-learning-exchange/myplanet/pull/1452
