### ISSUE TITLE
Submissions: Image document with realm submission_id

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1449]
It's possible that this is from a survey started on the tablet that has not synced, but there is no matching submission for the below image document that was synced to my Planet CouchDB.  It's important to link the image to a test/survey submission.

![image](https://user-images.githubusercontent.com/9203229/70813133-fe7b1300-1d96-11ea-8d37-5509f42c12f3.png)

**Comment by leomaxi** [comment]
There is exam id linked to photo. The user might not submit finally the quiz. Photos are taken when user answers each question not when quiz is finally submitted on myPlanet.
