### ISSUE TITLE
Our News - Show Replies Crash

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/myplanet#1501]
The app crashes when clicking on `SHOW REPLIES(1)`

![OurNews](https://user-images.githubusercontent.com/22177989/72628316-ab572b80-3913-11ea-8d6c-e1e714808143.png)

![showreplies](https://user-images.githubusercontent.com/22177989/72628322-af834900-3913-11ea-996a-de17f31f135c.png)

![appcrash](https://user-images.githubusercontent.com/22177989/72628382-d2adf880-3913-11ea-80ca-0346a066246d.png)

**Comment by rrijal53** [comment]
fixed in https://github.com/open-learning-exchange/myplanet/pull/1504
