### ISSUE TITLE
take survey : takes photo's

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1517]
Taking a survey from `Surveys` takes photos as the person takes the survey. This `must not` be the case.

<img width="966" alt="Screenshot 2020-01-22 at 9 33 08 AM" src="https://user-images.githubusercontent.com/2836302/72882317-555efb00-3cfa-11ea-8651-6a3facf26c04.png">

<img width="1007" alt="Screenshot 2020-01-22 at 9 33 21 AM" src="https://user-images.githubusercontent.com/2836302/72882421-80494f00-3cfa-11ea-95b1-eeeaf1d9fd6b.png">

13 question in survey took 13 photos`

<img width="1609" alt="Screenshot 2020-01-22 at 9 36 12 AM" src="https://user-images.githubusercontent.com/2836302/72882650-df0ec880-3cfa-11ea-8149-c1473c7f41ee.png">

**Comment by rrijal53** [comment]
fixed in https://github.com/open-learning-exchange/myplanet/commit/0abf5301f4842fbb21a6b480fc41724f7a522e61
