### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1530]
Note that initially after upgrading to 0.6.78 I had to clear the myPlanet app data a few times before I could load myPlanet.  That may affect this issue.

After hitting sync after the upgrade it opened a download dialog that made no progress after ~10 minutes.  I closed that, and now I am seeing the below in the download dialog with error message and still no progress is made.  I tried clearing app data, but the same error message came up again.

![Screenshot_2020-01-27-22-03-36 (1)](https://user-images.githubusercontent.com/9203229/73232953-ff9fae00-4152-11ea-9ba6-0ffbcf1c1cd3.png)

There is no log in the Planet database for this event.

EDIT: Adding correct image

**Comment by leomaxi** [comment]
Resolved...  news file download
