### ISSUE TITLE
community leaders : Load more

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1538]
<img width="948" alt="Screenshot 2020-01-29 at 4 07 30 PM" src="https://user-images.githubusercontent.com/2836302/73374039-7bb00800-42b1-11ea-8a20-d692b7788bd8.png">

**Comment by anthonyhvo12** [comment]
Good idea. There should be a button that allows users with proper administrative rights to view the full list of users/community leaders rather than members using tablets.

**Comment by rlam20** [comment]
referenced in #3455 and subsequent pr in #3457
