### ISSUE TITLE
Add story : story with image

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1551]
Should be able to add a new story with images.
<img width="1277" alt="Screenshot 2020-02-02 at 9 57 01 PM" src="https://user-images.githubusercontent.com/2836302/73622244-fb6a0980-4606-11ea-87f0-9b4b6eb3f792.png">

**Comment by rrijal53** [comment]
@leomaxi  you need to enable beta feature for adding image.
