### ISSUE TITLE
update main toolbar to match planet

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/myplanet#1561]
Looks like the Home has changed to myDashboard, and Community is first instead of last.

Planet

![planet main title bar](https://user-images.githubusercontent.com/22177989/73863490-caa3f300-4805-11ea-827c-206ea87ea8c0.png)

myplanet

![myplanet main titlebar](https://user-images.githubusercontent.com/22177989/73863500-d0013d80-4805-11ea-9e88-09219f5a6514.png)

**Comment by leomaxi** [comment]
Lets keep it the same.  We are yet to  get confirmation for this change. It might even change on Planet

**Comment by leomaxi** [comment]
Confirmed  to keep it same
