### ISSUE TITLE
News: New data format

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1588]
We modified the data format for News in Planet.  The format is described in this Google Document: https://docs.google.com/document/d/1dMIb-ilpG2dkxTxn670CLTVnWt59coV3SzIDvinksZs/edit.

The old format should still be readable.  The properties `viewableBy` and `viewableId` should no longer be written to new documents, and instead we should write that information in `viewIn`.

**Comment by rrijal53** [comment]
fixed in https://github.com/open-learning-exchange/myplanet/pulls
