### ISSUE TITLE
share news with community

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1592]
<img width="1034" alt="Screenshot 2020-02-19 at 11 16 13 AM" src="https://user-images.githubusercontent.com/2836302/74851528-5d19bb80-5309-11ea-982f-2eb7b552bbe3.png">

**Comment by rrijal53** [comment]
Data structure
<img width="548" alt="Screen Shot 2020-02-21 at 21 37 27" src="https://user-images.githubusercontent.com/9145217/75049491-62862a00-54f2-11ea-8390-f7dc909ca822.png">
