### ISSUE TITLE
survey from nation data bag 

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1609]
Survey taken on myPlanet must not have `id@null` in parentId as bellow. It must be `ONLY the parent Id`
<img width="756" alt="Screenshot 2020-02-25 at 1 36 21 PM" src="https://user-images.githubusercontent.com/2836302/75276526-4a552a00-57d4-11ea-9a16-05f79d3f535c.png">

Survey taken on myPlanet doesn't have `questions` array in database.. It. is missing. All surveys from nation must still contain questions in database and should not be removed as shown above..

**Comment by rrijal53** [comment]
done
