### ISSUE TITLE
Next step in course is disabled

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1618]
<img width="888" alt="Screenshot 2020-02-28 at 12 28 54 PM" src="https://user-images.githubusercontent.com/2836302/75570938-2e48c700-5a26-11ea-9c9c-b4af0e5639a9.png">

**Comment by rrijal53** [comment]
@leomaxi  it's working  here
![Screenshot_1582987961](https://user-images.githubusercontent.com/9145217/75609770-6689fb80-5b33-11ea-8795-88e2632299a4.png)

**Comment by leomaxi** [comment]
Might be the course
