### ISSUE TITLE
team activities

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1635]
It. always appends tablet details to already existing teamVisits
<img width="661" alt="Screenshot 2020-03-10 at 5 12 13 PM" src="https://user-images.githubusercontent.com/2836302/76434751-ff2f3f80-63ad-11ea-8728-ff1e08566a8b.png">

**Comment by rrijal53** [comment]
fixed in https://github.com/open-learning-exchange/myplanet/commit/0b2eba4517a78493365f19ec194926aff16efc3a
