### ISSUE TITLE
Team and enterprise visits adds up

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1638]
Instead of visits being counted/sorted by team. / enterprise Id, it adds up when you visit team A and. Enterprise B

<img width="1594" alt="Screenshot 2020-03-13 at 2 10 34 PM" src="https://user-images.githubusercontent.com/2836302/76628335-77c00880-6534-11ea-8d92-322654b54c17.png">

**Comment by rrijal53** [comment]
done
