### ISSUE TITLE
members shouldn't be able take quiz if they have not joined a course

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1646]
<img width="1276" alt="Screenshot 2020-03-18 at 4 03 33 PM" src="https://user-images.githubusercontent.com/2836302/76981173-1633db80-6932-11ea-8815-18cd532265cf.png">

**Comment by rrijal53** [comment]
@leomaxi they can take quiz if they have not joined a course, you mean they should not be able to take test ??

**Comment by leomaxi** [comment]
Exactly.. Shouldnt
