### ISSUE TITLE
adding images to community - crash

### ISSUE THREAD

**Issue by nvrqt03** [open-learning-exchange/myplanet#1654]
when adding images to news stories in community, app is crashing. 

![crash image 1](https://user-images.githubusercontent.com/22177989/77187550-a98c1e80-6aa2-11ea-9e73-b3b001777147.png)

![crash image 2](https://user-images.githubusercontent.com/22177989/77187564-af81ff80-6aa2-11ea-8f7f-babb9f637374.png)

![crash image 3](https://user-images.githubusercontent.com/22177989/77187581-b3ae1d00-6aa2-11ea-872a-270f22f41cdc.png)

**Comment by rrijal53** [comment]
not exist in new version
