### ISSUE TITLE
Adding Functionality to Profile Dropdown Button

### ISSUE THREAD

**Issue by Vncentou422** [open-learning-exchange/myplanet#166]
Creating a drop down menu for when you click the profile button much like on the web end

<img width="270" alt="screen shot 2018-08-02 at 2 54 13 am" src="https://user-images.githubusercontent.com/5431055/43567362-83943cb8-95ff-11e8-9dc9-427f6b4f9328.png">
<img width="272" alt="screen shot 2018-08-02 at 2 54 48 am" src="https://user-images.githubusercontent.com/5431055/43567365-85a6e514-95ff-11e8-9e7a-b4551eda966f.png">

**Comment by leomaxi** [comment]
I don't think they should be able to change password on tablet when device is offline (Not connected to server)
