### ISSUE TITLE
Create member from myPlanet

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1690]
Creating user / become a member on from my planet create erroneous members

**Comment by rrijal53** [comment]
@leomaxi  i have successfully created user from myplanet and it is working in both myplanet and planet.
<img width="909" alt="Screen Shot 2020-04-15 at 21 10 36" src="https://user-images.githubusercontent.com/9145217/79355633-a54a0880-7f5d-11ea-9834-e8808cb79542.png">

**Comment by leomaxi** [comment]
The webview on some devices seems to be the problem. So lets create the form in-app and submit to. planet for processing and response.
