### ISSUE TITLE
Enterprises : Not showing on planet

### ISSUE THREAD

**Issue by meharshahani** [open-learning-exchange/myplanet#1716]
Enterprises created on myPlanet do not show up on the planet.

**Comment by leomaxi** [comment]
Database data anomaly.
**Working / Showing metadata**
<img width="573" alt="Screenshot 2020-05-01 at 4 01 18 PM" src="https://user-images.githubusercontent.com/2836302/80819770-2a235c00-8bc5-11ea-8f0d-bfa2331fc75c.png">

**Errorneous data from myPlanet**
<img width="712" alt="Screenshot 2020-05-01 at 4 01 10 PM" src="https://user-images.githubusercontent.com/2836302/80819812-3dcec280-8bc5-11ea-9878-cdc671d3b0ab.png">
