### ISSUE TITLE
create tutorials for Health

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1729]
Step by step walkthrough of myHealth

**Comment by anastasia21112** [comment]
[myHealth Tutorial.pdf](https://github.com/open-learning-exchange/myplanet/files/4903589/myHealth.Tutorial.pdf)

**Comment by anastasia21112** [comment]
[myHealth Tutorial.pdf](https://github.com/open-learning-exchange/myplanet/files/4903689/myHealth.Tutorial.pdf)

^^more steps on how to enable beta functionality

**Comment by gautamsethi1** [comment]
> [myHealth Tutorial.pdf](https://github.com/open-learning-exchange/myplanet/files/4903689/myHealth.Tutorial.pdf)
> 
> ^^more steps on how to enable beta functionality

I think the tutorial looks good. Maybe adding pictures would make it easier to follow?

**Comment by leomaxi** [comment]
Done
