### ISSUE TITLE
Health: Created duplicate user

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1738]
I'm not sure what happened.  Here's what I noted doing:

1. Created a new member **ttt**
2. Added an examination for that member
3. Synced once while logged in, did not see member on Planet so synced again from the login screen
4. When I try to select member I see two of the same member
5. Neither entry has the examination I added on it

![Screenshot_2020-05-11-22-45-54](https://user-images.githubusercontent.com/9203229/81632932-79456a00-93d9-11ea-8990-2b694e3c17e0.png)

**Comment by leomaxi** [comment]
Validating member creation
