### ISSUE TITLE
Health: New member information sometimes not syncing

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1739]
1. Created a new member
2. Added an examination
3. Synced, multiple times
4. No data synced to `health` database for that member
5. A `key` and `iv` were created in the usersdb for that member (good!)
6. Added a health profile for that member in case that is required for syncing
7. Still no doc with that member's user _id in the `health` database

**Comment by leomaxi** [comment]
Fixed in https://github.com/open-learning-exchange/myplanet/pull/1747
