### ISSUE TITLE
Health: New patient encryption key incorrect

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1751]
I created a new patient offline with 0.7.77, reconnected via wifi, and then synced with Planet.

The encryption key sent to Planet was incorrect.  Now the member's health data is inaccessible on myPlanet, and errors are thrown in Planet.

**Comment by rrijal53** [comment]
Done  in https://github.com/open-learning-exchange/myplanet/pull/1747 this pr

**Comment by leomaxi** [comment]
Fixed in https://github.com/open-learning-exchange/myplanet/pull/1747
