### ISSUE TITLE
Health: validate examination inputs 

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1758]
'temperature': { min: 30, max: 40 },
 'pulse': { min: 40, max: 120 },
 'height': { min: 1, max: 250 },
'weight': { min: 1, max: 150 },
bp min 60/40 max 300/200

**Comment by paulbert** [comment]
Temperature, Height, and Weight should be limit to one decimal place and Blood Pressure should not allow any decimal places.
