### ISSUE TITLE
Show name in list instead of username

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1767]
Name is. Leonard. Mensah instead of learner
<img width="465" alt="Screenshot 2020-05-26 at 5 24 48 PM" src="https://user-images.githubusercontent.com/2836302/82931107-e595a100-9f75-11ea-85ce-0c1e13b3e732.png">

**Comment by rrijal53** [comment]
@leomaxi  i think we should not change this , as name can be null .
<img width="1060" alt="Screen Shot 2020-05-29 at 21 45 14" src="https://user-images.githubusercontent.com/9145217/83280006-b68d6280-a1f5-11ea-99d3-2191f639ff63.png">

**Comment by rrijal53** [comment]
done
