### ISSUE TITLE
Health: Incorrect data in user documents

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1770]
The encrypted data in health documents with the same `_id` as the user id should only have 3 or 4 properties (other than `_id` and `_rev`.

`profile`: An object with emergency contact information, notes, and special needs.  Same format as before.
`events`: (optional, no longer used) An array of objects with health examination information.  Old way of storing these, so no new data should be added to this.
`lastExamination`: A timestamp representing the last time the person was examined.
`userKey`: The randomized key to identify the person's examination documents.

All four of these fields should be encrypted.  Right now `lastExamination` is missing.

In addition, there are many unencrypted fields that should not exist on these documents.

### Correct Data (after decryption)
![image](https://user-images.githubusercontent.com/9203229/83031282-5d111200-a002-11ea-86c3-bed940972d75.png)

### Incorrect Data (after decryption)
![image](https://user-images.githubusercontent.com/9203229/83031497-9ea1bd00-a002-11ea-977a-7bafac3838b9.png)

**Comment by rrijal53** [comment]
done
