### ISSUE TITLE
Health: Every documented updated with sync

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1772]
All of the health documents are updated after syncing.

This isn't ideal for a few reasons.

- Every time a tablet syncs a new copy of that data is stored on the database until it does it's compaction runs.
- If there is some sort of sync error or bad data on the tablet, every health document could be affected instead of just the ones managed on that tablet.

**Comment by leomaxi** [comment]
Keep track and sync only health records related to members whose health records were updated.
