### ISSUE TITLE
Implement New Calendar Library 

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/myplanet#1783]
<img width="554" alt="Screen Shot 2020-05-29 at 8 13 59 AM" src="https://user-images.githubusercontent.com/33525794/83275811-8c4f8c80-a184-11ea-8aef-c74143da1755.png">

The calender is very small, hard to navigate, and can not create any new events or click on specific days to view events. Need to find a new library to update the calender in the app.

**Comment by rrijal53** [comment]
https://medium.com/@Patel_Prashant_/android-custom-calendar-with-events-fa48dfca8257

**Comment by gautamsethi1** [comment]
https://console.cloud.google.com/marketplace/details/google/calendar-json.googleapis.com?id=84f291c9-2585-4af1-a78b-09c53a78202f&pli=1
