### ISSUE TITLE
Help / Tutorial

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1785]
Show navigation tutorial as help on first-time use
Have help as a menu item 
Showcase / walkthrough the app and its functions

**Comment by rrijal53** [comment]
Showcase view
https://github.com/deano2390/MaterialShowcaseView

**Comment by rrijal53** [comment]
We can show help page when user opens app for the first time. Like this...
https://www.androidcodefinder.com/wp-content/uploads/2018/03/intro-slider-using-viewpager.jpg

**Comment by anastasia21112** [comment]
Some guided functionality steps **LOGIN PAGE**: 
![image](https://user-images.githubusercontent.com/49795308/83375906-b4f6a280-a38d-11ea-97b5-12d7570944de.png)
**Press the Sync Button to Sync your Planet account data with your myPlanet application data**

![image](https://user-images.githubusercontent.com/49795308/83375942-d2c40780-a38d-11ea-8225-2bcf4727252c.png)
**Press the Settings Button to access your myPlanet/Planet account server settings to properly set up your syncing process.**

**Comment by anastasia21112** [comment]
Some guided functionality steps **HOME PAGE** 
* ![Home Tab](https://user-images.githubusercontent.com/49795308/83376314-21be6c80-a38f-11ea-81b9-374b50fb1114.png)
**Navigate to the Home Tab to access your dashboard with your library, courses, and teams**  

* ![Library Tab png](https://user-images.githubusercontent.com/49795308/83376344-37339680-a38f-11ea-81ac-e034be56ac1d.png)
**Navigate to the Library Tab to access resources in your community**   

* ![Courses Tab](https://user-images.githubusercontent.com/49795308/83376374-4b779380-a38f-11ea-82f7-f9f4904af425.png)
**Navigate to the Courses Tab to access the courses (exams, questions, lessons) within your community**  

* ![Enterprises Tab](https://user-images.githubusercontent.com/49795308/83376426-62b68100-a38f-11ea-8fd0-0051686cb9c0.png)
**Navigate to the enterprises tab to search through a list of enterprises within your community**  

* ![Community Tab](https://user-images.githubusercontent.com/49795308/83376450-77931480-a38f-11ea-9a5d-b75bfaff01dd.png)
**Navigate to the Community tab to access the news, community leaders, calendar, services, and finances involved within your community**
