### ISSUE TITLE
Health: Specify Required and Optional Fields

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/myplanet#1806]
### Problem

In the Examination form, it would be helpful to specify whether a field is required or not. For required ones, put a * or another special character next to them. As in practice, some fields may not apply, like Diagnosis if the user does not have one.

### Screenshot

<img width="345" alt="Screen Shot 2020-06-03 at 12 51 55 PM" src="https://user-images.githubusercontent.com/43098273/83665126-03c45800-a599-11ea-8324-ed46e1322e2b.png">

**Comment by leomaxi** [comment]
Have a confirmation dialogue when submitting examination stating the vitals that are empty.
