### ISSUE TITLE
Add in Units for New Examinations on myPlanet

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/myplanet#1808]
When I go to add an examination on myPlanet, no units are recommended which makes entering data less exact and may cause some confusion. 

**Image:**
<img width="589" alt="Screen Shot 2020-06-05 at 7 44 28 AM" src="https://user-images.githubusercontent.com/33525794/83890412-9a5f5900-a700-11ea-924b-7c1657ad11fe.png">

**Solution:**
Add in something like Height (in.) for each of the fields.

**Comment by anastasia21112** [comment]
similar issue here: https://github.com/open-learning-exchange/myplanet/issues/1804

**Comment by gautamsethi1** [comment]
> similar issue here: #1804

Sorry about the confusion, I'll close this issue right now.
