### ISSUE TITLE
Health : Show full name first

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1815]
Change  member list must show **fullname  (id)**  not id (fullname)

Member name  must be  out of the bracket must and member  ID rather in bracket

<img width="970" alt="Screenshot 2020-06-05 at 3 37 03 PM" src="https://user-images.githubusercontent.com/2836302/83895671-8c322c80-a742-11ea-830b-e756d6c7d431.png">

**Comment by rrijal53** [comment]
done
