### ISSUE TITLE
Feedback:- optional email address field 

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1816]
Feedback dialog on Login screen must request for an email address (optional) which will help us get back to online users especially when they are not connected to any community/nation.

Feedback Data will  be sent to ????? if device is not connected/linked with  any nation/community
<img width="961" alt="Screenshot 2020-06-05 at 3 41 19 PM" src="https://user-images.githubusercontent.com/2836302/83896418-a9b3c600-a743-11ea-9b71-227511b3a6e8.png">

**Comment by dogi** [comment]
emails are part of the profile of the learner
