### ISSUE TITLE
Sync Feedback without Community/Nation

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1817]
## Description
Find a way to sync the feedback that a user reports without them being connected to the Planet server

## Solutions
* Find a certain database which is most efficient (comment below what resources you find)

**Comment by rrijal53** [comment]
Parse database :  https://parseplatform.org/

**Comment by anthonyhvo12** [comment]
This answer might be helpful too: https://stackoverflow.com/questions/58854907/how-to-keep-a-local-database-to-store-data-in-an-android-app-when-the-app-is-off. It suggests using Android Room for local storage.

**Comment by rlam20** [comment]
Conflicts with google privacy policies on emails
