### ISSUE TITLE
Health: Input validation for vision and hearing

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/myplanet#1829]
### Problem
Currently there is no input validation for vision and hearing data in Health.
![Screen Shot 2020-06-10 at 12 45 12 PM](https://user-images.githubusercontent.com/43098273/84295188-439aba80-ab18-11ea-8232-438f33720579.png)
![Screen Shot 2020-06-10 at 12 47 18 PM](https://user-images.githubusercontent.com/43098273/84295409-8b214680-ab18-11ea-8863-bd00d9b7ea4a.png)

### Solution
Add input validation for vision.
For hearing, we can possibly include a link to the person's audiogram.

**Comment by leomaxi** [comment]
Thanks @anthonyhvo12 , No validation is currently required when  I asked around. So closing this issue. Good Job
