### ISSUE TITLE
User has to Sync Before Requesting to Join Team

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1835]
## Description  
After creating a team, a user has to sync their myPlanet application to Planet before being able to request to join the team. Although it is somewhat implied, a first time user may forget to repeatedly sync any new information created on myPlanet. If a user forgets, it will seem as if the button is not working when requesting to join. 

## Solution  
Add a note when creating the team that all teams must first be synced to Planet before other users can request to join.

**Comment by mattscodeans** [comment]
I think this is a good idea. Probably can be done by editing the XML format.

**Comment by rlam20** [comment]
outdated
