### ISSUE TITLE
User logged out when syncing

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/myplanet#1837]
### Description
Right now when a user hits "Sync Now" (top right corner), they will be required to log out of myPlanet and log in again.

![Screen Shot 2020-06-12 at 12 07 00 PM](https://user-images.githubusercontent.com/43098273/84522770-3b23ba80-aca5-11ea-9299-9c3fe602e890.png)

### Solution
Allow in-app syncing without logging out and logging in again.

**Comment by mattscodeans** [comment]
I do agree that we should allow users to sync without having to resign in. I think a quick and effective temporary solution would be to add an alert message that warns the user syncing will require the user to log back in.
