### ISSUE TITLE
Uploading Resource on myPlanet does not appear on Planet

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/myplanet#1840]
**Problem**
When I uploaded a file to the resources folder in a team on myPlanet, it does not appear not Planet.

**Steps to Reproduce**
Create a new team. 
Upload a file on myPlanet app. 
Check Planet to see if the resource was uploaded. 

**Images** 
<img width="605" alt="Screen Shot 2020-06-12 at 9 57 25 AM" src="https://user-images.githubusercontent.com/33525794/84527885-8af98600-ac93-11ea-9f5d-baa1554ce9a6.png">

<img width="1680" alt="Screen Shot 2020-06-12 at 9 57 43 AM" src="https://user-images.githubusercontent.com/33525794/84527896-8d5be000-ac93-11ea-904f-3b3268ba59d6.png">

**Comment by rrijal53** [comment]
@gautamsethi1 did you sync after adding resource?

**Comment by gautamsethi1** [comment]
> @gautamsethi1 did you sync after adding resource?

Yes. I had also made a comment from the app, and it appeared on Planet. For some reason the resource will not appear.
