### ISSUE TITLE
Showcase on  portrait mode needs to be done differentl 

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1852]
<img width="494" alt="Screenshot 2020-06-19 at 2 34 28 PM" src="https://user-images.githubusercontent.com/2836302/85144180-5741d180-b23a-11ea-83a1-a57463079777.png">

**Comment by leomaxi** [comment]
walk through screen of myplanet does not cover whole screen in 10" tablet we have. It has space on bottom of screen which is clickable

**Comment by rlam20** [comment]
showcase is no longer a feature
