### ISSUE TITLE
Option to Create Custom Label in Teams Chat

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1855]
## Description  
When making a message in a chat, you can label it with something such as "Help Wanted" or "Offer". There should be an option to create a custom label such as a name of a current task, casual message, or something else pertaining to the specific team. 

## Screenshots 
![Screen Shot 2020-06-19 at 9 20 48 AM](https://user-images.githubusercontent.com/49795308/85149535-a540e000-b20e-11ea-9e67-78e0669f1e4d.png)

**Comment by mattscodeans** [comment]
I think this is a good idea. I don't know the best way to reorganize the UI, but we need to include a textedit somewhere in the menu.
