### ISSUE TITLE
Suggestion: Maintain Consistency in Wording for Examination Form

### ISSUE THREAD

**Issue by mattscodeans** [open-learning-exchange/myplanet#1861]
**Issue**
Currently, the examination form features two Text Edits with "Observation and Notes" and "Diagnosis Note". I feel like using "Note" and "Notes" is rather inconsistent. I suggest revising the text to feature "Observations and Notes" and "Diagnosis Notes" in order to maintain consistency throughout the examination form.

![image](https://user-images.githubusercontent.com/42992553/85158963-b63f2080-b211-11ea-9368-cac12e61f883.png)

**Solution**
This can be accomplished by making small edits in the XML file.

**Comment by anastasia21112** [comment]
Yeah I think you can just edit the values/strings xml file
