### ISSUE TITLE
Bug: Team resources added on myPlanet don't show up after syncing

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1877]
## Description
When adding a resource to a team on myPlanet and then syncing with Planet, the resource disappears. 

## Screenshots
![Screen Shot 2020-06-24 at 9 50 10 AM](https://user-images.githubusercontent.com/49795308/85589070-7c4e8f80-b600-11ea-9eb3-39e4cc8b0ca3.png)
![Screen Shot 2020-06-24 at 9 50 20 AM](https://user-images.githubusercontent.com/49795308/85589083-7fe21680-b600-11ea-9bba-5233085e966f.png)
![Screen Shot 2020-06-24 at 9 50 51 AM](https://user-images.githubusercontent.com/49795308/85589099-82447080-b600-11ea-95b3-47487463476d.png)

## Steps to Recreate
* Add a resource/document to a team on myPlanet
* Click sync now
* View team resources again

**Comment by gautamsethi1** [comment]
Repeat, already mentioned this issue in #1840.

**Comment by anastasia21112** [comment]
@gautamsethi1 thank you! sorry for the mistake.
