### ISSUE TITLE
Grammar Issues 

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/myplanet#1880]
**Problem:**

There are some issues with the grammar in the User Profile:
<img width="512" alt="Screen Shot 2020-06-24 at 9 34 44 AM" src="https://user-images.githubusercontent.com/33525794/85596482-9c7d4f00-b5fe-11ea-832d-48220803e491.png">

There is some awkward phrasing, and there is a noun/verb disagreement.

**Comment by anastasia21112** [comment]
good catch!
