### ISSUE TITLE
Team: Settings not available for teams created on myPlanet

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/myplanet#1884]
### Description

For teams created on Planet, the team will not show up on dashboard which would otherwise lead to the Team Fragment. 

### Screenshots
Full List of Teams

<img width="345" alt="Screen Shot 2020-06-24 at 1 03 44 PM" src="https://user-images.githubusercontent.com/43098273/85600606-9ba6e600-b61b-11ea-960c-5aba12502bac.png">

On Dashboard
<img width="342" alt="Screen Shot 2020-06-24 at 1 03 57 PM" src="https://user-images.githubusercontent.com/43098273/85600525-9053ba80-b61b-11ea-9f1c-13604b4797d9.png">

**Comment by leomaxi** [comment]
myTeams on the dashboard refer to team/s that the user is part of.  Not a list of available teams. In the screenshot provided all the other teams are pending approval..  But user is already part of "Planet team" that is why that can be seen on the dashboard..
