### ISSUE TITLE
Add Other Disease Option to Examination Form

### ISSUE THREAD

**Issue by mattscodeans** [open-learning-exchange/myplanet#1885]
**Issue**
Currently, the examination form includes a few selected diseases and categories of diseases. However, I think we should add an other disease option with a textbox to indicate what exact disease it is. There are countless possible diseases and instead of creating an extremely long list, having an other option can cover lesser known diseases without adding an entire new option.

Current disease selection:
![image](https://user-images.githubusercontent.com/42992553/85600867-b0c34b00-b602-11ea-9b19-c05fa8713524.png)

**Solution**
Include other option in the array of diseases, and add a textEdit to specify the other disease.

**Comment by anthonyhvo12** [comment]
Great suggestion!
