### ISSUE TITLE
Bug: Add Documents Button Doesn't Work After First Run

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1887]
## Description
In teams, if the user wants to add a document using the yellow 'add document' button, it won't work after the first run (or maybe at all). 

## Steps to Recreate
* Go to a team that you're in
* Go to resources
* Click the yellow "add document" 

## Pictures
![image](https://user-images.githubusercontent.com/49795308/85867996-f1e46800-b786-11ea-8e16-997d5e6f0c84.png)

**Comment by rrijal53** [comment]
Working for me , are you getting any error in logcat? 
<img width="324" alt="Screen Shot 2020-06-26 at 20 21 30" src="https://user-images.githubusercontent.com/9145217/85869441-65b85c00-b7eb-11ea-9eb0-656a0e05293e.png">

**Comment by anastasia21112** [comment]
Logcat prints this every time I click it: "oneway function results will be dropped but finished with status OK and parcel size 4"

**Comment by leomaxi** [comment]
> Logcat prints this every time I click it: "oneway function results will be dropped but finished with status OK and parcel size 4"
I get a similar error after second  time clicking button
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
