### ISSUE TITLE
Health: Exit confirmation dialog shown when submitting examination

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/myplanet#1893]
### Description
When the user adds an examination in Health, the exit confirmation dialog pops up along with the "Added successfully" message

### Screenshot
<img width="428" alt="Screen Shot 2020-06-26 at 11 47 25 AM" src="https://user-images.githubusercontent.com/43098273/85876316-8a88e100-b7a3-11ea-844a-8ca79561b346.png">

**Comment by mattscodeans** [comment]
Was there any information that you inputted into the examination form? I haven't been able to reproduce the bug.

**Comment by anthonyhvo12** [comment]
@mattscodeans I inputted only the fields in Vitals.

**Comment by rrijal53** [comment]
done in https://github.com/open-learning-exchange/myplanet/pull/1904
