### ISSUE TITLE
Include Example Format in Hint of Blood Pressure TextEdit for Examination Form

### ISSUE THREAD

**Issue by mattscodeans** [open-learning-exchange/myplanet#1894]
**Issue**
Blood pressure currently must be inputted as systolic/diastolic. However, unlike Body Temperature, Pulse Rate, Height, and Weight, there is nothing that indicates the units/format. I suggest adding (sys/dia) or some similar example format to the hint of the Blood Pressure TextEdit.

Current Blood Pressure in Examination Form:
![image](https://user-images.githubusercontent.com/42992553/85878352-69b59100-b78d-11ea-9622-b2fb20447630.png)

**Solution**
Modify the XML to include the example format of blood pressure.

**Comment by leomaxi** [comment]
**Systolic / Diastolic**
