### ISSUE TITLE
Health: Diagnoses not saved in health examination

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/myplanet#1900]
### Description

The diagnoses are not saved when the user submits a health examination.

### Screenshot

<img width="425" alt="Screen Shot 2020-06-26 at 1 07 17 PM" src="https://user-images.githubusercontent.com/43098273/85882908-1d2e7d80-b7ae-11ea-900f-c61830ddcd9f.png">

<img width="422" alt="Screen Shot 2020-06-26 at 1 07 52 PM" src="https://user-images.githubusercontent.com/43098273/85882886-156ed900-b7ae-11ea-93ee-c8cc7613cd0d.png">

**Comment by anthonyhvo12** [comment]
@rrijal53 did you mention that this data was supposed to be encryted and not viewable?

**Comment by rrijal53** [comment]
@anthonyhvo12  is it encrypted but should be visible. I m fixing this issue.

**Comment by rrijal53** [comment]
done
