### ISSUE TITLE
Education About All: Add sketching feature

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1915]
## Description
In the lesson plans for younger audience, a lot of the lesson consists of drawing/brainstorming. On a tablet, it would be effective to add a sketching feature for the kids. They would be able to draw their assignments and then turn it in.

**Comment by mattscodeans** [comment]
I think this is a great idea, but I have a suggestion. It might be too tasking to have to implement the sketching ourselves. There are many sketch apps on the android store (like SketchBook). We can guide the user to download such an app and provide instructions on how to upload their sketches from the external app to the assignment.

**Comment by leomaxi** [comment]
Not relevant any longer
