### ISSUE TITLE
Education About All: Shareable Document 

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/myplanet#1916]
King of like kindle, show that other students have already highlighted parts of a document. The teacher has the option to make a document public and allow for students to mark-up documents, and all students see the annotations. 

Example: 
![preview-4](https://user-images.githubusercontent.com/33525794/86272055-d6140400-bb82-11ea-88ca-1ad18ada8d88.png)

**Comment by leomaxi** [comment]
Not relevant any longer..  they can  use teams
