### ISSUE TITLE
Education Above All: Notebook Feature

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1921]
## Description
A lot of students in general as well as the students in this program would enjoy taking notes. In the app, there is no set place to store all notes taken. 

## Solution
We should implement a notebook feature which is a section of the app where kids can take notes through typing and store each note in the notebook section. They should be able to highlight their notes as well and be able to access them based on date added or the title.

**Comment by leomaxi** [comment]
Not relevant any longer
