### ISSUE TITLE
Date Formatting

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1924]
![image](https://user-images.githubusercontent.com/49795308/86482901-16ed5380-bd10-11ea-91ea-bcd0127ee955.png)
The date needs a space between the week day abbreviation and the date number.

**Comment by avin-sharma** [comment]
@anastasia21112  I am unable to reproduce this, I see spaces on the version I am running

![Screenshot_1593795029](https://user-images.githubusercontent.com/6264813/86487388-e9ae9e80-bd2b-11ea-87be-b77f25e29318.png)

**Comment by gautamsethi1** [comment]
I am also unable to reproduce this issue (refer to the image below).

<img width="1279" alt="Screen Shot 2020-07-09 at 10 54 57 AM" src="https://user-images.githubusercontent.com/33525794/87073756-c0ca5580-c1d2-11ea-938a-c61a190524dd.png">
