### ISSUE TITLE
Button not Functioning

### ISSUE THREAD

**Issue by gautamsethi1** [open-learning-exchange/myplanet#1946]
In the image below, there is a button labeled "RESOURCES[1]", which when clicked, does not appear to serve any purpose. 

<img width="1277" alt="Screen Shot 2020-07-09 at 11 35 52 AM" src="https://user-images.githubusercontent.com/33525794/87077684-5caa9000-c1d8-11ea-92f5-feecd8a55b3b.png">

Any clarification as to whether this is a bug, or I have misunderstood the button's function would be much appreciated.

**Comment by rrijal53** [comment]
I m seeing resource dialog , are you seeing any error in logcat??
<img width="347" alt="Screen Shot 2020-07-10 at 20 02 38" src="https://user-images.githubusercontent.com/9145217/87164338-691e0e00-c2e8-11ea-99e9-3c33155ed2be.png">
<img width="337" alt="Screen Shot 2020-07-10 at 20 02 53" src="https://user-images.githubusercontent.com/9145217/87164334-67544a80-c2e8-11ea-9e56-67198b19d098.png">

**Comment by gautamsethi1** [comment]
I am not sure why it was not working for me yesterday. However, I am now able to see the resources upon clicking the button. Thank you for the clarification.
