### ISSUE TITLE
unable to navigate to next step in course

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1947]
Completed step one but next button is still disable
<img width="332" alt="Screen Shot 2020-07-10 at 20 01 13" src="https://user-images.githubusercontent.com/9145217/87164192-31af6180-c2e8-11ea-8152-a5075f7df3eb.png">

**Comment by leomaxi** [comment]
Having the same issue after taking the test, the Next button is not enabled
