### ISSUE TITLE
course detail ui issue in phone

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#1948]
<img width="341" alt="Screen Shot 2020-07-10 at 20 04 28" src="https://user-images.githubusercontent.com/9145217/87164535-99fe4300-c2e8-11ea-9a9a-4a480465ffdf.png">

**Comment by Okuro3499** [comment]
this was already resolved
![Screenshot_20240304_140235_myPlanet](https://github.com/open-learning-exchange/myplanet/assets/64019708/8d144ff5-10ce-4a93-a322-5bb02947872d)
