### ISSUE TITLE
Add Background Text to indicate that no Course was found by Filter

### ISSUE THREAD

**Issue by mattscodeans** [open-learning-exchange/myplanet#1952]
** Issue **
Currently, when the user uses the course filter and finds no courses that match the criteria, this screen is shown:
![image](https://user-images.githubusercontent.com/42992553/87167499-e9f5ef00-c281-11ea-9b77-717317259dfd.png)

However, there is no indication to the user that no courses match the specified filter. This could lead to confusion, especially since the search bar does not collapse when no courses are found.

** Solution **
When no courses match the filter, add to the center of the screen a EditText that states "No searches were found" or something similar.

**Comment by Okuro3499** [comment]
[Screen recording 2023-12-18 19.51.25.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/6904a115-b822-4a0c-901c-ce028696f268)
