### ISSUE TITLE
Planet name not updated after updating user profile

### ISSUE THREAD

**Issue by anthonyhvo12** [open-learning-exchange/myplanet#1964]
### Description
After the user updates their names, changes are not reflected in the planet name on the top left corner (username is still shown instead).

<img width="335" alt="Screen Shot 2020-07-10 at 11 03 49 PM" src="https://user-images.githubusercontent.com/43098273/87174939-236e3f00-c302-11ea-86f2-bece583e57cb.png">

**Comment by rlam20** [comment]
works after logging out then logging in- navigation bar will get reworked
