### ISSUE TITLE
Community Tab Layout

### ISSUE THREAD

**Issue by anastasia21112** [open-learning-exchange/myplanet#1967]
## Description
The tabs in the community activity are kept to fill half of the screen. It would visually make more sense for them to just stretch out across the screen. 

## Screenshot
![Screen Shot 2020-07-10 at 10 15 15 AM](https://user-images.githubusercontent.com/49795308/87175921-8de99580-c296-11ea-98f2-6cc6bde71fd8.png)

**Comment by avin-sharma** [comment]
We could center the tabs, what do you think?
