### ISSUE TITLE
Sync of myplanet 

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#1976]
Install myplanet 0.8.48
Connect to rpi network
Setup config to 192.168.2.1
Click on Sync from setup
It keeps spinning for longer than 15 min and still not complete
NOTE: it is tested on demo.ole.org:21980 with very few resource and courses

If you try to sync from arrow on login page it complete quickly and also able to login after that

**Comment by lmmrssa** [comment]
Install myPlanet 0.8.48
Connect to rpi network
Setup config to 192.168.2.1 and just save
now on login page click on sync icon
it will start syncing and then give message server not found
close app
reopen app
click on sync icon on login page
it sync correctly and everything works

**Comment by leomaxi** [comment]
Please be clear on the server.. 192.168.2.1 or demo.ole.org:21980

Is it on HTTP / HTTPS

**Comment by lmmrssa** [comment]
it is happening with 192.168.2.1 i mentioned other url so you can check how much content it has

**Comment by rlam20** [comment]
several reworks on sync
