### ISSUE TITLE
myPlanet text is cut off

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#1978]
myPlanet text below Logo is cut off on login page when there is no community setup.
Once there is community connected, myPlanet text completely get hidden

**Comment by leomaxi** [comment]
Screenshot please..

**Comment by lmmrssa** [comment]
https://drive.google.com/file/d/1-5UeVzXEATEiFvrCiPQu7tljBUyyNJp4/view?usp=sharing

**Comment by avin-sharma** [comment]
Which device was this screenshot taken on?

**Comment by rlam20** [comment]
reworked
