### ISSUE TITLE
Community page

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#1981]
Community news : It gives **-** only or **-<name>** we should remove **-** if it is not two values
Also on leader: It gives empty **-** to admin user

**Comment by leomaxi** [comment]
How do you suggest we handle admin user details, that has been a long standing debate

 Note:-  myPlanet doesn't sync admin details because it is in only_users database of CouchDB. 

Suggestions will be extremely helpful

**Comment by lmmrssa** [comment]
**-** is also coming for other users not just admin

**Comment by leomaxi** [comment]
> **-** is also coming for other users not just admin

_A picture speaks a thousand words_ .. Adding an image would have explained this issue better
<img width="989" alt="Screenshot 2020-07-01 at 3 43 18 PM" src="https://user-images.githubusercontent.com/2836302/87430780-3bc9ac80-c5d5-11ea-96b7-22e60bb1af7b.png">
