### ISSUE TITLE
Enterprises : Task sync

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1995]
Checking / unchecking task as completed or not completed works on myPlanet BUT does not sync to database
Task state shows the same as before. Only changes when changed in Planet and synced back to myPlanet. 
<img width="1288" alt="Screenshot 2020-07-14 at 12 16 46 PM" src="https://user-images.githubusercontent.com/2836302/87424750-07052780-c5cc-11ea-82b4-1932b8fa3113.png">

After sync, it still shows completed
<img width="751" alt="Screenshot 2020-07-14 at 12 07 43 PM" src="https://user-images.githubusercontent.com/2836302/87424855-3e73d400-c5cc-11ea-9921-3aca6ffde923.png">

**Comment by rrijal53** [comment]
Working for me
<img width="376" alt="Screen Shot 2020-07-16 at 20 53 47" src="https://user-images.githubusercontent.com/9145217/87688321-8f3f2480-c7a6-11ea-9e11-902bd1448b24.png">

<img width="1401" alt="Screen Shot 2020-07-16 at 20 53 43" src="https://user-images.githubusercontent.com/9145217/87688309-8bab9d80-c7a6-11ea-9597-8c7fc005b891.png">
