### ISSUE TITLE
Login Screen: Can type in to community name

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#2001]
A bit of a strange one.  I tapped to focus on the username field before the bottom news panel came up.  When I started typing in the username the text was added to the front of the community name at the bottom instead of the username field.

![Screenshot_2020-07-14-11-53-04](https://user-images.githubusercontent.com/9203229/87448960-8abe1480-c5ca-11ea-8599-0e0896404985.png)

**Comment by gautamsethi1** [comment]
Unable to reproduce. When I tapped to focus on the username field, the community pop-up goes away for me.
