### ISSUE TITLE
Show disk space in full

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#2014]
- Let's make it a bit graphical with drive image ..

- Have to know total disk space and what is left eg. 4.3 / 6 GB

- Move it to the left blue area to keep the  login screen clean

<img width="1283" alt="Screenshot 2020-07-16 at 11 01 19 AM" src="https://user-images.githubusercontent.com/2836302/87663981-0ac3b600-c754-11ea-9445-096d032d6605.png">

**Comment by avin-sharma** [comment]
Does this look better? Should I change the text size or styling?

![Screenshot_1594952264](https://user-images.githubusercontent.com/6264813/87741335-455c3b80-c7b2-11ea-8c30-78317140548a.png)

**Comment by leomaxi** [comment]
> Does this look better? Should I change the text size or styling?
> 
> ![Screenshot_1594952264](https://user-images.githubusercontent.com/6264813/87741335-455c3b80-c7b2-11ea-8c30-78317140548a.png)

Yes, it does.. We need to have the external and internal image..
 I think what you have now is okay for external..
