### ISSUE TITLE
Wording Issue in Leave Team Alert Message

### ISSUE THREAD

**Issue by mattscodeans** [open-learning-exchange/myplanet#2029]
**Issue**
The alert message for trying to leave a team has some wording issues.
Here is the alert message:
![image](https://user-images.githubusercontent.com/42992553/87808429-8da94700-c80e-11ea-8870-840730c366df.png)

**Steps to Reproduce**
1. Enter a currently existing team.
2. Click on leave in the top right corner.

**Solution**
Change the message to the following:
Are you sure you want to leave this team?

**Comment by leomaxi** [comment]
> **Issue**
> The alert message for trying to leave a team has some wording issues.
> Here is the alert message:
> ![image](https://user-images.githubusercontent.com/42992553/87808429-8da94700-c80e-11ea-8870-840730c366df.png)
> 
> **Steps to Reproduce**
> 
> 1. Enter a currently existing team.
> 2. Click on leave in the top right corner.
> 
> **Solution**
> Change the message to the following:
> Are you sure you want to leave this team?

Good  Catch

**Comment by gautamsethi1** [comment]
Repeat issue, look at issue #1955

**Comment by mattscodeans** [comment]
I'll close this issue. Thanks for telling me gautam.
