### ISSUE TITLE
sync animation doesn't stop if sync error

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#2030]
sync animation doesn't stop when sync encounters errors / when the server is not found

**Comment by mattscodeans** [comment]
Can confirm, I was able to reproduce this issue.

**Comment by leomaxi** [comment]
> Can confirm, I was able to reproduce this issue.

To reproduce this, turn off your wifi /  connect your device to a different network and click on the sync icon located in the login screen.
