### ISSUE TITLE
Disk space on device

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#2070]
Disk  space on devices on the field report  erroneous values
![WhatsApp Image 2020-07-28 at 10 59 34](https://user-images.githubusercontent.com/2836302/88658628-426f1e00-d0c3-11ea-9277-43c9e94f3fe8.jpeg)

![WhatsApp Image 2020-07-28 at 11 11 28](https://user-images.githubusercontent.com/2836302/88658669-5286fd80-d0c3-11ea-9d18-5d5c58d8abc6.jpeg)

**Comment by leomaxi** [comment]
From android?
![WhatsApp Image 2020-07-28 at 10 59 34](https://user-images.githubusercontent.com/2836302/88658913-c0332980-d0c3-11ea-91c7-8cdacc7d5e47.jpeg)

**Comment by anthonyhvo12** [comment]
@avin-sharma can you verify the calculations again? I did some code refactoring with my latest PR (#2043) but that shouldn't have changed the logic of the code.
