### ISSUE TITLE
Track resource view when clicked on open resource

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#2085]
It should be from course step, course overview, resource detail
Should have detail of tablet

**Comment by leomaxi** [comment]
If I get this issue right, the suggestion is to separate resources viewed metadata from library/team/enterprise the ones viewed from courses. In that light, On open, we must record,

- When resource was opened
- Title of the resource (resource details)
- Who opened it,
- Which course it was opened from (id and title)
- Specific step in the course that the resource was opened from
- etc.
