### ISSUE TITLE
Track resource download

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#2087]
Should have detail of tablet and user used to download

**Comment by leomaxi** [comment]
- Track and save resource download completion of tablet
- Save these data in new DB since resource can be deleted  from the device by user clearing storage
- Sync this new tablet db in activity log/ somewhere on planet server

**Comment by rrijal53** [comment]
Already done
<img width="585" alt="Screen Shot 2021-01-29 at 20 24 16" src="https://user-images.githubusercontent.com/9145217/106288320-fd919300-626f-11eb-8cc1-f98e0d4396b0.png">
