### ISSUE TITLE
community news: adding a new story textbox error outline

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/myplanet#2255]
Adding a new community story the textbox an error outline even though the story is added, 
There is no acknowledgement that the story has been added(the form does not close and the error outline persists)

![Screenshot_20230727_162930_myPlanet](https://github.com/open-learning-exchange/myplanet/assets/48474421/21f4f55d-b030-4222-a4dc-4873eafa63ad)

**Comment by Okuro3499** [comment]
the outline is not of an error but for a focused edit text 
![image](https://github.com/open-learning-exchange/myplanet/assets/64019708/cdf6ae84-b312-4f74-bbc2-8b3ebd032d67)
![Screenshot 2023-08-11 15 52 48](https://github.com/open-learning-exchange/myplanet/assets/64019708/aaa8c422-eb6f-4d3a-89c6-eef4a7df35a6)
