### ISSUE TITLE
rethink tutorial at first time start

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/myplanet#2295]
remove?

**Comment by dogi** [comment]
maybe a easy way to skip
or instead of auto start to manually start

**Comment by Okuro3499** [comment]
based on the issues raised on [com.github.deano2390:MaterialShowcaseView](https://github.com/deano2390/MaterialShowcaseView/issues/108) the library does not support skip functionality

possible solutions to look at
finding and implementing an alternative library 
removing tuutorial
