### ISSUE TITLE
crash log uploaded message on sync

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/myplanet#2354]
Getting a `crash log uploaded` message when I sync the app using the sync icon. This is quickly followed with a `sync complete` message

![Screenshot_20230824_202911_myPlanet](https://github.com/open-learning-exchange/myplanet/assets/48474421/c7a016fc-e9ac-4abe-bdb0-a2c09e4f4575)

**Comment by Okuro3499** [comment]
@rlam20 `crash log uploaded` is just a success message of the uploading user does not need to see it
