### ISSUE TITLE
Settings Toggle Switch Clicks the whole row 

### ISSUE THREAD

**Issue by Mzazi25** [open-learning-exchange/myplanet#2468]
On the Settings Page, the switch buttons that toggles on and off, clicks the whole row instead of the switch button only. 
I have also tested the switch is triggered when I click any part of the row (Instead of the switch). 

I have tested this on phone and Tablet Emulator 

Here is a video to show this:

https://github.com/open-learning-exchange/myplanet/assets/95022986/d60688ec-6014-4ced-b83f-f78d9b870780

**Comment by Mzazi25** [comment]
> clicks on the whole row gives a user a wide touch area compared to having the click listener on the switch only. This is good the way it is 

Fair enough. 
It makes sense. I can close this?

**Comment by Okuro3499** [comment]
yes you can
