### ISSUE TITLE
let's update the README.md

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/myplanet#2686]

**Comment by Okuro3499** [comment]
![Screenshot 2023-12-08 14 09 43](https://github.com/open-learning-exchange/myplanet/assets/64019708/31d9ab32-1513-4ec6-a51c-bb89f09339b1)
![Screenshot 2023-12-08 14 10 13](https://github.com/open-learning-exchange/myplanet/assets/64019708/343a26a7-ddb5-4139-a0f8-235d50d74219)
![Screenshot 2023-12-08 14 10 22](https://github.com/open-learning-exchange/myplanet/assets/64019708/06e1f1fc-46f4-445f-a56c-41f17f84cbf2)
![Screenshot 2023-12-08 14 10 35](https://github.com/open-learning-exchange/myplanet/assets/64019708/df0b3ef3-eda0-4b58-94d9-53d51ed030de)

**Comment by xyb994** [comment]
- https://play.cuzi.workers.dev/
- https://github.com/badges/shields/issues/358#issuecomment-806235967
