### ISSUE TITLE
Save question choice issue 

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#305]
Question choice does not have unique id so it can not be saved on different table.

<img width="445" alt="screen shot 2018-10-25 at 7 47 17 pm" src="https://user-images.githubusercontent.com/9145217/47507270-9ff08e00-d891-11e8-976d-3f058cd76b72.png">

![screenshot_1540477309](https://user-images.githubusercontent.com/9145217/47507290-a7b03280-d891-11e8-8664-7aa997739fbc.png)

**Comment by leomaxi** [comment]
`You can not save choices on different table as its ID will never be unique. It was only set to be unique within question.`

**Comment by leomaxi** [comment]
`You can not save choices on different table as its ID will never be unique. It was only set to be unique within question.`

**Comment by paulbert** [comment]
@leomaxi @rrijal53 @lmmrssa The choice id should be unique within the document only.  It is there to keep track of which choice is the correct answer to the question.  What you have in the above picture isn't good because the correct answer is not stored for that question.
