### ISSUE TITLE
oops in enterprise chat

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/myplanet#3111]
Encountered a significant issue where attempting to add a message caused the application to become unresponsive and subsequently shut down.

**Suggestions for Consideration**:

Enterprise Chat Functionality: A critical review of the Enterprise chat feature is necessary to address the crash issue when adding messages.

![test1](https://github.com/open-learning-exchange/myplanet/assets/8721051/4b8a86b5-1e8f-4a75-9b93-d53e2ece99a5)
![test2](https://github.com/open-learning-exchange/myplanet/assets/8721051/8f27a5fa-f64f-4a01-9e00-bbbf80b6c790)

_Originally posted by @reganmaharjan in https://github.com/open-learning-exchange/myplanet/pull/3103#pullrequestreview-1870315421_

**Comment by Okuro3499** [comment]
duplicate #3109
