### ISSUE TITLE
Update on previously synced course does not reflect

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#320]
Tried to update course on planet and do sync again. But course still has same old data on myplanet. It does not seem to change.

**Comment by rrijal53** [comment]
Tested , but i've not found any issue : 

```Before```
![screenshot_1540912822](https://user-images.githubusercontent.com/9145217/47729511-62707400-dc88-11e8-831f-10d9ca369ab1.png)

```Added step, resource on the same course and synced again```
![screenshot_1540912994](https://user-images.githubusercontent.com/9145217/47729557-76b47100-dc88-11e8-83fb-b06de2aea884.png)

**Comment by lmmrssa** [comment]
I think it was because i used Sync (spinner) icon on left side not Sync button. Content only seem to sync by **Sync button** or automatic sync not from spinner
