### ISSUE TITLE
App crashes : App crashed during login

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#324]
<img width="1365" alt="screenshot 2018-10-30 03 20 08" src="https://user-images.githubusercontent.com/6964191/47681908-e2e49580-dbf2-11e8-9cd5-d6f68722d0ff.png">

**Comment by rrijal53** [comment]
@yuviii 
I've not found any issue , can you explain the issue in detail.

```screenshot```
![screenshot_1540911975](https://user-images.githubusercontent.com/9145217/47728184-f12fc180-dc85-11e8-990c-a09069006f55.png)

**Comment by rrijal53** [comment]
@yuviii  already fixed.
