### ISSUE TITLE
DialogBox in home

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#340]
![screenshot_20181104-074716](https://user-images.githubusercontent.com/6964191/47959239-b4a5f200-e006-11e8-926b-a2725fb8d289.png)

Every time home is opened, this dialog box appears. There is some option not to see again or see in after some time interval.

**Comment by leomaxi** [comment]
appears because resources arent downloaded yet. But shows up only when server is online / in reach
