### ISSUE TITLE
Shows NA in username though it is showing username in dashboard

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#345]
![screenshot_20181104-083459](https://user-images.githubusercontent.com/6964191/47959447-9e029980-e00c-11e8-82e8-4c753ebbd084.png)

**Comment by rrijal53** [comment]
@yuviii It is  showing fullname and email not username.

**Comment by yuviii** [comment]
@rrijal53 I think it would be better to use label as email for email and full name like below.

**Comment by leomaxi** [comment]
Resolved
