### ISSUE TITLE
Says Connection failed

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#346]
Getting no connection message though having internet connection.

![test](https://user-images.githubusercontent.com/6964191/47959484-b921d900-e00d-11e8-9a19-07ca7d585ac7.png)

**Comment by rrijal53** [comment]
@yuviii  Showing connection failed, because the requested file is not available in server. We can change it into other meaningful message.

**Comment by lmmrssa** [comment]
@yuviii @rrijal53 is right its when there is not attachment for any resource. It should not be high priority right now.
