### ISSUE TITLE
Disable non functioning items

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#353]
![screenshot_20181106-234158](https://user-images.githubusercontent.com/6964191/48083723-096f8580-e21e-11e8-979a-1e2cdb7268a2.png)
![screenshot_20181106-233624](https://user-images.githubusercontent.com/6964191/48083735-0d9ba300-e21e-11e8-8704-49944c6eb556.png)

**Comment by dogi** [comment]
@yuviii think we should split this issue into more concrete pieces ...

**Comment by lmmrssa** [comment]
Closing this issue for now as rating is already worked on. Team function is disabled.
