### ISSUE TITLE
typo on when adding resource

### ISSUE THREAD

**Issue by rlam20** [open-learning-exchange/myplanet#3530]
![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/58f6ba2f-dd84-4feb-9cf8-8aaa46a5612e)
![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/c3c245b3-0e4e-4e97-9f4b-495f255297a1)

**Comment by Okuro3499** [comment]
good catch. after updating the english string file maybe translate to the other languages and update
