### ISSUE TITLE
prevent steps scroll if course not joined

### ISSUE THREAD

**Issue by Okuro3499** [open-learning-exchange/myplanet#3547]
learner should not be allowed to scroll through the course steps if the course is not joined

https://github.com/open-learning-exchange/myplanet/assets/64019708/961697fc-0258-45a2-86a1-41d48a680616

**Solution**
Only show the next and previous button if course is joined

**Comment by ewhang5** [comment]
Could we redirect back to the "Courses" page if the user selects "cancel"?
