### ISSUE TITLE
guests can still select courses via checkbox even when they cannot join courses

### ISSUE THREAD

**Issue by ewhang5** [open-learning-exchange/myplanet#3588]
To my understanding, selecting the courses is so that you can join the courses you have selected. If this is the case, guests should not be able to select courses through checkbox.
<img width="246" alt="Screenshot 2024-06-09 at 3 01 12 PM" src="https://github.com/open-learning-exchange/myplanet/assets/59347000/143402ec-c418-4d9b-aafa-ae2dc9369172">

**Comment by Okuro3499** [comment]
you can hide the select all and also the checkboxes for guest learner
