### ISSUE TITLE
teams: every tab shows a member list 

### ISSUE THREAD

**Issue by rlam20** [open-learning-exchange/myplanet#3592]
This is the case for every tab except for the 'chat' tab 
this issue only shows up on teams the logged in user is not a part of 

![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/37eacf00-cb34-4048-a801-3eb460e46d11)
![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/e48444a7-2768-4e0c-8b4d-daad64245aea)
![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/331c9cd1-f61f-4d45-9f64-e2b7fe744981)

solution: make it so only the 'members' tab displays the member list

**Comment by Okuro3499** [comment]
which server are you connected to? which apk version
I was not able to recreate this

https://github.com/open-learning-exchange/myplanet/assets/64019708/4df8f992-4ceb-4fba-90b9-95fb1462c8f3

**Comment by rlam20** [comment]
version is 0.15.76 connected to planet.learning

**Comment by rlam20** [comment]
it seems that it only affects teams that you are not a part of

**Comment by Okuro3499** [comment]
investigating this will communicate a way forward

**Comment by Okuro3499** [comment]
this happens for public teams/enterprises you could fix the data to display in the correct tabs
