### ISSUE TITLE
myCourses being visible to guests even when they can never join a course

### ISSUE THREAD

**Issue by ewhang5** [open-learning-exchange/myplanet#3602]
Should we hide myCourses from guests if they do not have the functionality to ever join a course?
<img width="270" alt="Screenshot 2024-06-12 at 11 49 29 AM" src="https://github.com/open-learning-exchange/myplanet/assets/59347000/883fa6cb-a889-4d69-9f15-6282a3024053">

**Comment by Okuro3499** [comment]
that would mean also removing the mycourses in Dashboard
![Screenshot_20240614_175301](https://github.com/open-learning-exchange/myplanet/assets/64019708/eb284ac6-22a8-4f71-9ce6-2e0fd82b5b3d)

**Comment by xyb994** [comment]
Looks like this did confuse someone.

From https://discord.com/channels/1079980988421132369/1131244649902772235/1260270809281462465

> it was unclear whether I could add courses or not, because there wasn't any button to do so (I imagine you have to be a member to add a course).

Should we keep the add course button but come up with a dialog/toast indicating only registered users can add a course?

**Comment by ewhang5** [comment]
> Looks like this did confuse someone.
> 
> From https://discord.com/channels/1079980988421132369/1131244649902772235/1260270809281462465
> 
> > it was unclear whether I could add courses or not, because there wasn't any button to do so (I imagine you have to be a member to add a course).
> 
> Should we keep the add course button but come up with a dialog/toast indicating only registered users can add a course?
> 
> Also a side question, should a guest user be allowed to rate since they cannot even "take" the course?

I personally think that we should get rid of the myCourses options for guests. I think @xyb994 brought up a great point and that guests should not be allowed to rate courses. @Okuro3499 what do you think about this?

**Comment by Okuro3499** [comment]
we solved this by showing a dialog communicating to the guest user to become a member to access mycourses @xyb994 guest users are not able to rate courses
[Screen_recording_20240902_165939.webm](https://github.com/user-attachments/assets/4a3bfed7-3f9a-4186-8c11-e44ab4fab77f)

**Comment by xyb994** [comment]
> we solved this by showing a dialog communicating to the guest user to become a member to access mycourses @xyb994 guest users are not able to rate courses [Screen_recording_20240902_165939.webm](https://github.com/user-attachments/assets/4a3bfed7-3f9a-4186-8c11-e44ab4fab77f)

Looks good. I'm closing this!
