### ISSUE TITLE
actions: is the non beta version still working

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/myplanet#3658]
```
com.github.barteksc:android-pdf-viewer:3.2.0-beta.1
```

https://github.com/open-learning-exchange/myplanet/blob/15ca9bee081084d3a48d6608f4c184e4722d0175/app/build.gradle#L107C21-L107C72

**Comment by strawberrybread** [comment]
https://mvnrepository.com/artifact/com.github.barteksc/android-pdf-viewer
does not work with v2.6.0
