### ISSUE TITLE
App crashes: Taking surveys

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#380]
surveys -> take survey 
After finishing the survey app get crashed.
in my case i have taken first survey.

![screenshot_20181128-001210](https://user-images.githubusercontent.com/6964191/49104189-728a6c00-f2a5-11e8-80b7-1ddb8195aa16.png)

<img width="1361" alt="screenshot 2018-11-28 00 37 14" src="https://user-images.githubusercontent.com/6964191/49104332-c9904100-f2a5-11e8-86fb-912a9c48b8f9.png">

**Comment by rrijal53** [comment]
@yuviii  the problem was in mySurvey branch not in master, i've fixed the issue in existing PR. Please review again. https://github.com/open-learning-exchange/myplanet/pull/377
