### ISSUE TITLE
Add to library enable disable toggle not working

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#381]
when checkbox is toggled disabling and enabling of add to library works, but while resource page load i.e. when the menu library is clicked it is always enabled though none of any resource is selected.

![screenshot_20181128-003913](https://user-images.githubusercontent.com/6964191/49104557-5f2bd080-f2a6-11e8-945f-54eba5566a0c.png)
![screenshot_20181128-003920](https://user-images.githubusercontent.com/6964191/49104554-5a671c80-f2a6-11e8-90f9-941770579a3e.png)

**Comment by leomaxi** [comment]
resolved
