### ISSUE TITLE
app crashes when replying to a reply with an image

### ISSUE THREAD

**Issue by strawberrybread** [open-learning-exchange/myplanet#3827]
[reply_with_image_crash.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/75f6751a-1a7d-47b9-abd9-3f6a8492ca80)

**Comment by Okuro3499** [comment]
@strawberrybread could you add the error message being logged

**Comment by strawberrybread** [comment]
> @strawberrybread could you add the error message being logged

I tried recreating the crash but when running the current beta, the reply box no longer chows an `ADD IMAGE` option.

**Comment by Okuro3499** [comment]
no worry I recreated and got the error

**Comment by Okuro3499** [comment]
@strawberrybread to recreate go to settings switch this setting off then back on the add image button will be visible
![Screenshot_20240722_143319 (1)](https://github.com/user-attachments/assets/6c73c00e-3ba8-4e96-aa27-dce24a536cbc)
