### ISSUE TITLE
back arrow disappears after switching languages

### ISSUE THREAD

**Issue by strawberrybread** [open-learning-exchange/myplanet#3935]
[Screen_recording_20240724_114308.webm](https://github.com/user-attachments/assets/441f4af7-d26b-4867-a0c8-23c4f3191d51)

**Comment by Okuro3499** [comment]
not able to recreate this
[Screen_recording_20240724_191820.webm](https://github.com/user-attachments/assets/46c3b87e-673a-4848-ab63-684475ab43e1)

**Comment by rlam20** [comment]
also getting this issue- button seems to be there but the top bar isn't appearing
