### ISSUE TITLE
config: selected server 

### ISSUE THREAD

**Issue by rlam20** [open-learning-exchange/myplanet#3998]
![image](https://github.com/user-attachments/assets/ecfa6f6e-4647-4a01-a8bd-0b4a4dae7802)
maybe have the server you're currently on be highlighted

**Comment by ewhang5** [comment]
It should be highlighted. This most likely means that you have not synced, cleared your data, or failed your previous sync.

**Comment by rlam20** [comment]
> It should be highlighted. This most likely means that you have not synced, cleared your data, or failed your previous sync.

After I switch servers I get the successful sync message but the server I synced to isn't highlighted. Is that a result of clearing the data after a sync?

**Comment by ewhang5** [comment]
> > It should be highlighted. This most likely means that you have not synced, cleared your data, or failed your previous sync.
> 
> After I switch servers I get the successful sync message but the server I synced to isn't highlighted. Is that a result of clearing the data after a sync?

It should have it empty after the clear data but if you then chose to sync to the server after clearing the data it should be highlighted after the sync. If your issue still happens after this could you attach a screen recording if possible?
