### ISSUE TITLE
dark mode: selected dark mode option 

### ISSUE THREAD

**Issue by rlam20** [open-learning-exchange/myplanet#4003]
![image](https://github.com/user-attachments/assets/cd29543f-2aac-4890-92be-2be87fdf83b4)
have it so the current dark mode setting is selected

**Comment by Okuro3499** [comment]
resolved in #4134 

[Screen_recording_20240815_153440.webm](https://github.com/user-attachments/assets/f77bfdc2-43f7-4254-89a3-22d54ab010f0)
