### ISSUE TITLE
improve the message when community/local server not reachable 

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/myplanet#4055]
![image](https://github.com/user-attachments/assets/b72dc64a-c1bd-4900-a0c0-84f6d05e7230)

kinda asking if the are in the right wifi network to this local server (community)
for nations maybe ask if they are connected to the internet

**Comment by Okuro3499** [comment]
@dogi 
updated to 
`local`
device couldn't reach the server. check if you are connected to the correct Wi-Fi network for the local server (community)

`nation`
device couldn’t reach the server. check if you are connected to the internet and try again
