### ISSUE TITLE
Beta Rating feature

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#413]
Beta feature should not hide Rating of course. As showing rating is working fine. Just adding rating (event trigger) can be blocked by Beta feature.
![screenshot_1544198621](https://user-images.githubusercontent.com/2909490/49658383-08728380-fa6a-11e8-8abf-3e37d4314b6b.png)
![screenshot_1544198604](https://user-images.githubusercontent.com/2909490/49658391-0d373780-fa6a-11e8-8477-73599dff75c1.png)

**Comment by leomaxi** [comment]
Have rating as a different Beta feature switch
