### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#417]
When you do not have any item selected Action is disabled and grayed out as seen in image below
![screenshot_1544196880](https://user-images.githubusercontent.com/2909490/49660357-7c168f80-fa6e-11e8-808c-9e288e61d039.png)
If you select item then Action will be highlighted
![screenshot_1544196884](https://user-images.githubusercontent.com/2909490/49660384-8df83280-fa6e-11e8-99c8-cda2b2fbc603.png)
If you navigate to another fragment without unselecting items (may be go to library) and come back to courses then Action remains highlighted even when list does not have selection
![screenshot_1544196874](https://user-images.githubusercontent.com/2909490/49660444-b849f000-fa6e-11e8-9376-95e7adeac617.png)

**Comment by leomaxi** [comment]
Lets test and re-create issue if it still exist
