### ISSUE TITLE
settings: change language text to white

### ISSUE THREAD

**Issue by strawberrybread** [open-learning-exchange/myplanet#4179]
![image](https://github.com/user-attachments/assets/54f4f688-682d-4465-bf41-1d978092e578)

**Comment by deeppp15** [comment]
https://docs.google.com/document/d/1KzvZRvCwu6e1cZ29N-0pWP_pInISQH6Nbv8WLdlFvGo/edit?usp=sharing Check out this document for analysis on this issue and references.

**Comment by Okuro3499** [comment]
> https://docs.google.com/document/d/1KzvZRvCwu6e1cZ29N-0pWP_pInISQH6Nbv8WLdlFvGo/edit?usp=sharing Check out this document for analysis on this issue and references.

@deeppp15 create a pr with the changes you are suggesting
