### ISSUE TITLE
check version compatibility

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#419]
myPlanet will require to check version that planet supports and that is no longer supported.
then it should prompt user to upgrade application.
This will ensure that myplanet does not mesh with data in planet.
We also need to figure out what meta data myplanet will require for it and URL that planet can return to.
Related to https://github.com/open-learning-exchange/planet/issues/2688

**Comment by rrijal53** [comment]
I think, we should make meta data something like this.
```

Request : BASE_URL/get_meta_data

Response : 
{
"version_name": "v0.2.27",
"version_code" :  227,
"minSupportVersion" : 221,
"apk_url" : "APK_PATH"
.........
}

**Comment by yuviii** [comment]
@lmmrssa  agreed with @rrijal53  we can have one additional GET request API with the response containing the information of current release version. So when user open the app, app will check the installed version with the version available from server and prompt the user to update the new version via deeplink.

**Comment by lmmrssa** [comment]
We have introduced `/versions` as url to check myplanet version compatibility.

**Comment by rrijal53** [comment]
@lmmrssa  @dogi  @paulbert 
Let's add more field in the response i.e. app version code instead of version name. So it will be easier to compare.
<img width="610" alt="screen shot 2018-12-12 at 9 29 53 pm" src="https://user-images.githubusercontent.com/9145217/49880861-1b63ca00-fe55-11e8-8b95-046172ceebb8.png">
