### ISSUE TITLE
create an account to access this

### ISSUE THREAD

**Issue by Okuro3499** [open-learning-exchange/myplanet#4259]
`create an account to access this` toast keeps appearing even though learner has an account
![Screenshot_20240826_191117](https://github.com/user-attachments/assets/eb6d7329-f50d-4936-96cb-1e5829bea3b3)

**Comment by Kuljeet1998** [comment]
I tried re-creating this: it doesn't show up for me, am I missing something?

https://github.com/user-attachments/assets/eae891c3-d188-47b5-be6a-cd7acd535b27

**Comment by Okuro3499** [comment]
appears randomly trying to investigate it more
