### ISSUE TITLE
more visible text in dark mode

### ISSUE THREAD

**Issue by Okuro3499** [open-learning-exchange/myplanet#4260]
![Screenshot_20240826_190951](https://github.com/user-attachments/assets/d26508e3-eb2b-4472-bf79-7bc78dafcba0)

**Comment by Kuljeet1998** [comment]
@Okuro3499 instead of dark text 'surveys not available' I see 'submissions not available'

Refer the video.

https://github.com/user-attachments/assets/5d8a9f72-8c9f-43aa-aae5-0df1b1944916

**Comment by Okuro3499** [comment]
[Screen_recording_20240827_223935.webm](https://github.com/user-attachments/assets/01f9a198-d0ad-4bbb-8e92-5888afbfa10f)

**Comment by Kuljeet1998** [comment]
Can you please tell me what server are you on? @Okuro3499
