### ISSUE TITLE
notification bar coincides with app

### ISSUE THREAD

**Issue by Kuljeet1998** [open-learning-exchange/myplanet#4286]
Works fine until notifications are accessed. 
After notifications are viewed, the app and notification bar coincides.
Device: OnePlus 6t

https://github.com/user-attachments/assets/5a4b32f1-fb5b-48f2-90d7-2ec863aaec01

**Comment by Okuro3499** [comment]
I don't understand what the issue is

**Comment by Kuljeet1998** [comment]
The notification of bar of the phone and the header app of the app overlaps.

**Comment by Okuro3499** [comment]
I don't see the overlapping
