### ISSUE TITLE
User login is working even after tablet pin is changed in server

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#431]
**Myplanet app setting view**

![screenshot_1545399621](https://user-images.githubusercontent.com/6964191/50345230-62894380-0556-11e9-963d-1368c8f59e11.png)

**Server manager view**

<img width="1440" alt="screenshot 2018-12-21 19 25 37" src="https://user-images.githubusercontent.com/6964191/50345251-7af95e00-0556-11e9-8e45-59b220ef95bd.png">

**Comment by lmmrssa** [comment]
Tablet works offline so change in server will not stop myplanet from working. That is how we developed it. If pin changed it will be able to get new data or send data to server. But all old data will be available on tablet for it to be used. So this is not issue.
