### ISSUE TITLE
Leave and join in team detail :Team detail

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#432]
Inside myteam detail, when leave button is clicked it is changed to  request pending - it should change to request to join.
after request to change is clicked it should change to request pending.

Now even after i clicked leave button after going back and opening the same team detail it still shows the leave button.

![screenshot_1545400964](https://user-images.githubusercontent.com/6964191/50346300-1213e500-055a-11e9-96fb-e8ab0aa29f2d.png)
![screenshot_1545400971](https://user-images.githubusercontent.com/6964191/50346308-16d89900-055a-11e9-878c-9d9760da2bf4.png)
![screenshot_1545400984](https://user-images.githubusercontent.com/6964191/50346313-1a6c2000-055a-11e9-849c-bc415b6fc3bd.png)

**Comment by leomaxi** [comment]
Team UX and flow changed
