### ISSUE TITLE
Unexpected error after downloading the resources.

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#434]
![screenshot_1545406790](https://user-images.githubusercontent.com/6964191/50350345-fb27bf80-0566-11e9-9d8f-44086d3dde60.png)

**Comment by lmmrssa** [comment]
Can you specify more about what resource you tried to download. Mobile might not be able to open all resources.

**Comment by rrijal53** [comment]
@yuviii  @lmmrssa  i've found and fixed the problem. Please review this PR https://github.com/open-learning-exchange/myplanet/pull/439
