### ISSUE TITLE
filter not working: resources

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#435]
**Here pirate@work is still showing for the test label filter**

![screenshot_1545407031](https://user-images.githubusercontent.com/6964191/50350545-9882f380-0567-11e9-9c0c-bd3b5722b999.png)

**Comment by lmmrssa** [comment]
oh test is not added on filter right now :) you need to type space as well then label will be added below as chip then it filter. It is not by clicking on search. It is done so that you can add multiple label. So this is not issue
