### ISSUE TITLE
Rating not working inside the resource detail

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#436]
**Rated one star **
![screenshot_1545407269](https://user-images.githubusercontent.com/6964191/50350789-53ab8c80-0568-11e9-8167-4eee09bfbcfe.png)
**After submitting the rating is not changed**
![screenshot_1545407277](https://user-images.githubusercontent.com/6964191/50350739-2828a200-0568-11e9-81fc-df97e8dd4546.png)

**Comment by leomaxi** [comment]
Only changes after reload or page revisit

**Comment by yuviii** [comment]
@leomaxi I think it would be better to update the view after the successful server request response achieved in callback

**Comment by lmmrssa** [comment]
I don't know why its not working for you. I see rating being updated automatically. Can you have more test and update issue.

**Comment by leomaxi** [comment]
Beta function
