### ISSUE TITLE
App crashes when survey in sidebar menu clicked

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#438]
![screenshot_1545408629](https://user-images.githubusercontent.com/6964191/50351780-49d75880-056b-11e9-888b-6ee75266ae8c.png)

**Comment by lmmrssa** [comment]
It seems to be working for me.

**Comment by yuviii** [comment]
@lmmrssa i think its working because u already have the data stored locally in your device. Might be u can try after clearing the data of the app and retry again with login.

In my case i uninstall the app and again installed it and used the app.

**Comment by rrijal53** [comment]
@yuviii is it in your local db ?? please share the screenshot of the log cat so it will be easier to find the problem.

**Comment by yuviii** [comment]
@rrijal53
 i found this issues with submission as well. I guess possible both issues are caused because of same problem. Error raised in logcat

<img width="1369" alt="screenshot 2018-12-28 22 29 42" src="https://user-images.githubusercontent.com/6964191/50521938-67b73700-0af0-11e9-829f-73cade1fd5df.png">

**Comment by rrijal53** [comment]
@yuviii  the submission crash issue is already fixed.
