### ISSUE TITLE
make pending survey list text dark mode compatible

### ISSUE THREAD

**Issue by Kuljeet1998** [open-learning-exchange/myplanet#4388]
Change the list text to lighter color

![image](https://github.com/user-attachments/assets/fad9285c-e196-4a73-849e-040807368be3)

**Comment by deeppp15** [comment]
Hi @Kuljeet1998 I think this is a duplicate issue, checkout this PR: 

  https://github.com/open-learning-exchange/myplanet/pull/4357

**Comment by Kuljeet1998** [comment]
Thanks for pointing it out @deeppp15 . Closing this issue.

**Comment by Kuljeet1998** [comment]
Taken care of: https://github.com/open-learning-exchange/myplanet/pull/4357
