### ISSUE TITLE
duplicate notification of surveys on dashboard

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/myplanet#4394]
### Description 

Now that we have a notification section on homepage. I feel survey notifications are duplicated. 
The same notification is available twice.

![Screenshot_20240912-130948_myPlanet](https://github.com/user-attachments/assets/8d7cc667-33e7-40c0-a45d-d7d72e0df78d)

![Screenshot_20240912-130956_myPlanet](https://github.com/user-attachments/assets/f4e12b3c-965a-41c1-9fb1-1268598e65dd)

**Comment by Okuro3499** [comment]
@deeppp15 this branch is not merged yet so we still don't have the feature on the app

**Comment by deeppp15** [comment]
> @deeppp15 this branch is not merged yet so we still don't have the feature on the app

Okay , are we planning to merge this into the main app release ? @Okuro3499

**Comment by Okuro3499** [comment]
@deeppp15 You can work on this

**Comment by deeppp15** [comment]
Since It was decided that due to business needs we need both notifications
