### ISSUE TITLE
popup dialog action buttons are scrollable

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/myplanet#4436]
## Description

Action buttons on this dialog should be fixed and not scrollable

![image](https://github.com/user-attachments/assets/04fbed27-7311-401d-826d-dce0e385b7d7)

![image](https://github.com/user-attachments/assets/e563cdad-2f49-4739-b306-ea570e1baaae)

**Comment by Okuro3499** [comment]
this is a good issue but we have duplicate for this #3956. I think we can use the old issue and close this one

**Comment by deeppp15** [comment]
Closing since duplicate issue
