### ISSUE TITLE
sync pop up redesign

### ISSUE THREAD

**Issue by Okuro3499** [open-learning-exchange/myplanet#4445]
redesign for playstore to be able to select a  server
[121.webm](https://github.com/user-attachments/assets/30ab6bbc-0ea0-42b4-8991-8a4c8464c11e)

**Comment by deeppp15** [comment]
- Clear Data Button is not visible
- Redundant two switch or rename the dialog box of cloud. Currently the new structure pertaining to manual sync is a bit confusing for other users with less technical experience.

![image](https://github.com/user-attachments/assets/7e9d8d2f-3b0b-4815-aa34-de991abadc28)
