### ISSUE TITLE
push though issues

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#451]
- [x] User detail updated on planet is not synced on myplanet
- [x] User shelf is always replace by myplanet on planet when clicked on Refresh icon. Even when things are added on planet.
- [x] When clicked on sync shelf does not change One removed from planet still remains on myplanet and One removed on myplanet also remains on planet.

**Comment by rrijal53** [comment]
@leomaxi  i'll fix this on existing PR https://github.com/open-learning-exchange/myplanet/pull/425
