### ISSUE TITLE
playback music starts playing after a while 

### ISSUE THREAD

**Issue by Kuljeet1998** [open-learning-exchange/myplanet#4540]
Playback music starts playing after a video is viewed and the app is running in background. Faced this issue thrice now. Not sure what exactly are the steps to recreate it.

**Comment by Kuljeet1998** [comment]
Maybe linked to : https://github.com/open-learning-exchange/myplanet/issues/4080

**Comment by Okuro3499** [comment]
duplicate #4080

**Comment by Okuro3499** [comment]
Fixed by #4549
