### ISSUE TITLE
all wrong options in course Unit 2: The Moon

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/myplanet#4552]
## Description 

- Course the mooon has 3 same options which are all wrong/ invalid

##  Video

[All Wrong Answers in course Moon.webm](https://github.com/user-attachments/assets/4114ade4-17ee-4700-86a0-a6ac70e22709)

**Comment by Okuro3499** [comment]
@deeppp15 this is not an code issue but a mistake made during creation of the test

**Comment by deeppp15** [comment]
closing issue since its a data issue @Okuro3499  @dogi
