### ISSUE TITLE
courses not responsive on small screen

### ISSUE THREAD

**Issue by Okuro3499** [open-learning-exchange/myplanet#4574]
![Screenshot_20241008_133535](https://github.com/user-attachments/assets/99950da8-aa4b-40b6-982c-654ab6f9f52b)

**Comment by Kuljeet1998** [comment]
duplicate issue: https://github.com/open-learning-exchange/myplanet/issues/4565

**Comment by Okuro3499** [comment]
duplicate issue: #4565

**Comment by Okuro3499** [comment]
this was solved in #4566
