### ISSUE TITLE
stop download button on finished downloads

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/myplanet#4632]
In MyLibrary if you click a resource and view it.

The download dialog after completion shows stop download instead of finish or disappearing.

![image](https://github.com/user-attachments/assets/82715dd3-6592-4b5f-9663-1099b09221bd)

**Comment by Okuro3499** [comment]
also experienced the same
![Screenshot_20241016_131040](https://github.com/user-attachments/assets/2df76aef-46ff-423e-a33e-4993becd853c)
