### ISSUE TITLE
Reducing apk size

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#465]
Currently we have >39mb size of apk, need to think of way of reducing apk size
[Reducing apk size documentation](https://developer.android.com/topic/performance/reduce-apk-size)

**Comment by rrijal53** [comment]
@yuviii  The apk size big because of realm database.
The possible solution may be :  https://medium.com/mindorks/when-using-realm-for-android-makes-your-app-heavy-93c56c0d1c98

**Comment by leomaxi** [comment]
Already implemented
