### ISSUE TITLE
mycourses steps mismatch

### ISSUE THREAD

**Issue by Kuljeet1998** [open-learning-exchange/myplanet#4658]
Bugs:
- Case 1: Step starts w `0` (refer image)
- Case 2: When in-progress course is viewed, `previous` button should be visible.
- Steps are mismatched in general 

https://github.com/user-attachments/assets/33976aae-0935-4973-9b97-9f1d65ba3a87

![image](https://github.com/user-attachments/assets/f31379de-7d5b-461c-859a-06aa257236d0)

**Comment by Okuro3499** [comment]
for Case 1: Step starts w 0 (refer image) that is how it is supposed to be since you are not viewing any step

**Comment by Okuro3499** [comment]
duplicate #4605
