### ISSUE TITLE
save resource activity not language compatible

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/myplanet#4692]
## Description

- The current language is Nepali but all of the button and static descriptions are in English

## Screenshot

![image](https://github.com/user-attachments/assets/cc869ea8-54a7-4955-a617-899fb81bf23f)

**Comment by Okuro3499** [comment]
@deeppp15 this might help https://discord.com/channels/1079980988421132369/1229436065090371616/1295453417832976466
