### ISSUE TITLE
guestLogin: communitiy voices unavailable for guests

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/myplanet#4698]
## Description

- Without logging in we are showing voices in communities on login page.
- But if a guest logs in he is unable to see voices in communities page.

## Screenshot

![image](https://github.com/user-attachments/assets/1366a6ec-88bb-4cb5-aa3c-c06bb08f86a2)

**Comment by markoeltiger** [comment]
Hello @deeppp15  , can i take it?
