### ISSUE TITLE
Library: Disable the download resource button if it does not have attachments

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#474]
It would be better to have download resource button disabled, As in right side(Planet) of screen the download icon is disabled if it does not have attachment

<img width="1424" alt="screenshot 2019-01-04 23 30 07" src="https://user-images.githubusercontent.com/6964191/50702450-13c0cb00-1079-11e9-98d0-208b0fce5d31.png">

**Comment by leomaxi** [comment]
Resolved
