### ISSUE TITLE
# Rahul Singh

### ISSUE THREAD

**Issue by rah-uls** [open-learning-exchange/myplanet#4810]
# Rahul Singh

| Location            | Timezone      | OS                         |
| ------------------- | ------------- | -------------------------- |
| Noida, Uttar Pradesh | IST (UTC +5:30) | Windows 11 22631.4541 |

## About Me

Hello! I'm **Rahul Singh**, a passionate **Android Developer** currently pursuing a Bachelor's in Computer Science. With experience in Kotlin, Java, and Firebase, I aim to build intuitive and user-friendly mobile applications. I love solving problems and learning new technologies, and I'm always eager to contribute to real-world projects.

## Skills

- **Programming Languages:** Kotlin, Java,
- **Frameworks/Libraries:** Volley, Firebase, sql
- **Tools:** Android Studio, Git, Postman, Firebase

## Projects

- **Weather App**:  Developed An Android Application Using Java And The API To Display Real-Time Weather Information. Implemented.

- **Contact Saving App**:  Developed A Contact Saving Application..

## Connect with Me

- [LinkedIn](https://www.linkedin.com/in/rahul-singh-769438220/)
- [Github](https://github.com/rah-uls)
- [Email](rs9110719@gmail.com)

> I am looking forward to working on innovative projects and contributing to the tech community. Let's connect!

_Originally posted by @rah-uls in https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/3480#issuecomment-2501769888_

**Comment by xyb994** [comment]
It seems the profile markdown we requested was added to the issue description and cross referenced here as a new issue, which might have caused confusion. Could you please review the first steps instructions carefully to ensure the correct process is followed? Closing this for now, feel free to reach our in discord if there's additional context or clarification needed.
