### ISSUE TITLE
Make myplanet installation without need to manually uninstall

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#483]
Right now user needs to uninstall previous version to install new version. We need to make sure that new version can replace old version. My assumption is it could be related to signature of apk. We do not have signature that matches between different versions so android is taking it as same package build by different organization (group).
Also we need to deploy production version not debug version.

**Comment by rrijal53** [comment]
Using TravisCI to securely build and deploy a signed apk : 
https://android.jlelse.eu/using-travisci-to-securely-build-and-deploy-a-signed-version-of-your-android-app-94afdf5cf5b4

**Comment by rrijal53** [comment]
done
