### ISSUE TITLE
[Bug] Screen replication issue in chat section

### ISSUE THREAD

**Issue by Avinash-Codes** [open-learning-exchange/myplanet#4886]
Description:
When navigating to the chat section, if the chat icon is pressed multiple times, the app creates multiple instances of the same screen. This causes the user to press the back button multiple times to return to the previous screen.

Steps to Reproduce:

Navigate to the chat section.
Tap the chat icon multiple times.
Observe that multiple instances of the screen are added.
Press the back button repeatedly to confirm the issue.
Expected Behavior:
Pressing the chat icon multiple times should not replicate the screen. Subsequent taps should be ignored if the user is already on the chat screen.

Actual Behavior:
Multiple instances of the chat screen are added to the navigation stack.

Screenshots/Video:

[Screen_recording_20241217_175546.webm](https://github.com/user-attachments/assets/bec650f9-5ad5-4827-997a-23243ca3cede)

**Comment by Okuro3499** [comment]
@Avinash-Codes this might help https://chatgpt.com/share/6761a46a-dd54-800e-8d2a-f5be46d1bb1c
