### ISSUE TITLE
Course : Rating bar is still visible in course list even when beta function is turned off.

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#496]
![screenshot_1547824849](https://user-images.githubusercontent.com/9145217/51395663-6617e680-1b65-11e9-95c7-b5ccadcbca72.png)

**Comment by lmmrssa** [comment]
It is ok to show rating bar but it should not be possible to do rating.

**Comment by rrijal53** [comment]
@lmmrssa 👍
