### ISSUE TITLE
Test and remove exam from beta

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#510]

**Comment by rrijal53** [comment]
@leomaxi @lmmrssa  haven't found any issue with exam. comment if you guys found any.

**Comment by rrijal53** [comment]
Test cases : 
- [ ] Take Exam
- [ ] Submission
- [ ] Upload answers to couch db
- [ ] Validate exam data

**Comment by leomaxi** [comment]
Exams / courses now out of beta
