### ISSUE TITLE
embedded PDF reader

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#52]

**Comment by leomaxi** [comment]
Open pdf document type with an-app pdf reader.

**Comment by onlyserenity** [comment]
I researched this and I found two options for this issue:
* Use the built-in _PdfRenderer_ class (API 21+)
* Use external library [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer) (Any API)
Which option would you like me to proceed with?
