### ISSUE TITLE
Dashboard : My teams items are different from server and in mobile app

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#535]
**In server, It is showing only 5 teams**

<img width="1440" alt="screenshot 2019-02-01 21 58 59" src="https://user-images.githubusercontent.com/6964191/52134906-c3835b80-266c-11e9-822f-f4985a0da8c6.png">

**In Mobile app, it is showing 10 items**

![device-2019-02-01-215738](https://user-images.githubusercontent.com/6964191/52134999-f4fc2700-266c-11e9-90d9-1b98df3231b5.png)

**Comment by leomaxi** [comment]
Resolved in latest version
