### ISSUE TITLE
progress bar click

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#537]
On course list view. User can click on **Tick** icons of progress of course user has joined to. Clicking on those icons change color of progress bar status (Completion red color). But it does nothing, neither it opens that step nor does it actually update the status. So it is confusing. Same bar does nothing on course view. So can we make it similar on list view as well.

**Comment by leomaxi** [comment]
The entire progress bar must will have to be changed to reflect what planet has / a `bar`. 
Now that is works . well, we can focus on the look.
