### ISSUE TITLE
Take Course quiz (change finish to Submit)

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#553]
Take Course quiz (change finish to Submit)..
Last question then becomes finish

**Comment by jazdao** [comment]
Hi @leomaxi, where can I access the course quiz on the app?  The only button I see is the "Opt-Out of Course" button.

**Comment by rrijal53** [comment]
@jazdao Goto settings and enable beta functionality, then go to course detail, you'll get take test button there .

**Comment by jazdao** [comment]
@rrijal53 Got it, thanks!

**Comment by rrijal53** [comment]
@jazdao  yes
