### ISSUE TITLE
ResourceDetail: if no text present  show NA instead '?' and blank space

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#583]
![screenshot-1550246541922](https://user-images.githubusercontent.com/6964191/52868473-8db19d00-316b-11e9-8033-3f3bd1f1452b.jpg)

**Comment by rrijal53** [comment]
@yuviii  It is showing '?'  because  author name is '?' in the db. 
<img width="431" alt="screen shot 2019-02-15 at 9 54 36 pm" src="https://user-images.githubusercontent.com/9145217/52868771-4ed01700-316c-11e9-8991-d4b95ec12aab.png">

**Comment by yuviii** [comment]
@rrijal53 Great, you can add the NA for empty case.

**Comment by leomaxi** [comment]
Must be just as planet
