### ISSUE TITLE
Doing logout and pressing sync on the top left side of screen causing crash

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#584]
Steps i did:
1. Changed the dashboard my resource items in the myplanet and sync to server
2. sync to server by logging out from myplanet
3. Again changed the item from my resource in dashboard of planet
4. pressed sync in myplanet to pull the changes

After these steps app freezes for around 2 minute and app crashed.

![screenshot-1550247095594](https://user-images.githubusercontent.com/6964191/52869462-ceaab100-316d-11e9-9b4e-01f1242e5a8f.jpg)

**Comment by rrijal53** [comment]
@yuviii  haven't found the issue, is this issue still exist ??

**Comment by leomaxi** [comment]
Resolved
