### ISSUE TITLE
myLibrary: video resource sometimes dose not play

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#610]
Addition and subtraction from dev doesn't play on myPlanet

**Comment by rrijal53** [comment]
@leomaxi 
I haven't found the issue, it is working in my device.
![screenshot_1551197957](https://user-images.githubusercontent.com/9145217/53428357-c296dd00-3a12-11e9-9b8f-08bdb9bafb97.png)

**Comment by rrijal53** [comment]
@leomaxi   please add the logcat error.

**Comment by leomaxi** [comment]
It just doesn't play. No cash, no error.. Nothing.

**Comment by leomaxi** [comment]
Working now..
