### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#671]
Auto update of my Planet is not working

**Comment by lmmrssa** [comment]
https://www.openssl.org/docs/manmaster/man1/enc.html

**Comment by rrijal53** [comment]
Travis Android implementation example : 
https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4
https://github.com/harmittaa/travis-example-android

**Comment by rrijal53** [comment]
@leomaxi @lmmrssa  Auto update is working without uninstalling old version . Tested with these 2 recent release v0.3.28 and v0.3.29 :)
