### ISSUE TITLE
Resource without attachment.

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#674]
If there is resource without any attachment then adding that in **myLibrary** will give popup to download. After download it shows Download success. Also Button on Resource view change from Download to Open Resource but once you navigate to some other page and come back. It again shows popup to download. And also Button on Resource view change back to Download.

**Comment by rrijal53** [comment]
@lmmrssa 
In my case :
It is saying file not found.
![Screenshot_1553654956](https://user-images.githubusercontent.com/9145217/55046979-5340f700-506b-11e9-91ed-a54bdc7bac40.png)

And download/open button is not visible if there is no attachment.
![Screenshot_1553655093](https://user-images.githubusercontent.com/9145217/55047051-81bed200-506b-11e9-949d-922ab6f14369.png)

**Comment by leomaxi** [comment]
Works now
