### ISSUE TITLE
BellApp theme breaking

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#675]
Beta feature Bell Theme is not showing user visit clearly. Also **Submissions** **Email** **Surveys** are too small so it will difficult to click on.
Also Text **myLibrary** **myCourses** are hidden

Profile section looks ok when there is no top navbar. But buttons are still small 
Also Text **myLibrary** **myCourses** are visible but broken (only partly visible)

**Comment by leomaxi** [comment]
Fixed in PR  #731
