### ISSUE TITLE
Wifi switcher

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#677]
Beta functionality Wifi Switcher shows Green when wifi is off. And Red when on. Which looks confusing as RED usually means warning :) and I assumed its off and Green on.

Using wifi functionality is working. But it is not checking current status of WIFI when showing icon. It changes when it is triggered by application. It will be nice if it will show current status of Wifi when application starts as well.

**Comment by leomaxi** [comment]
Green means saving battery, and red means draining battery.. It was discussed to change the red to white since red is confusing.

**Comment by leomaxi** [comment]
Needs to be removed from beta version and abandoned

**Comment by leomaxi** [comment]
Not required any longer
