### ISSUE TITLE
ourLibrary: Once the collections is selected there is no option to remove independently.

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#679]
Once collections are  selected, to remove collection there is only way to clear and reselect collection again.

if there are selected tags already, when the collection dialogbox opens it should show the tags selected with the checkbox checked.

![Screenshot_1553273900](https://user-images.githubusercontent.com/6964191/54840110-5434fa00-4cf4-11e9-96b2-15b5aab47a79.png)

**Comment by leomaxi** [comment]
https://github.com/open-learning-exchange/myplanet/issues/676
