### ISSUE TITLE
Download Resource: Getting different response for same resource when try to download

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#680]
In first click in `Download Resource` button.
=======
![Screenshot_1553274893](https://user-images.githubusercontent.com/6964191/54841168-cb6b8d80-4cf6-11e9-80c9-1f9fc8f68dc9.png)

in Second Click 
===========
![Screenshot_1553274882](https://user-images.githubusercontent.com/6964191/54841205-e1794e00-4cf6-11e9-837f-d6de5bf46eb9.png)

in Third click
==========

![Screenshot_1553274905](https://user-images.githubusercontent.com/6964191/54841224-eb02b600-4cf6-11e9-9af5-3cea4d62ceb4.png)

**Comment by yuviii** [comment]
**Logs produced in android studio**

<img width="1344" alt="Screenshot 2019-03-22 23 06 47" src="https://user-images.githubusercontent.com/6964191/54841387-50ef3d80-4cf7-11e9-96e9-57e10b956523.png">

<img width="1369" alt="Screenshot 2019-03-22 23 07 31" src="https://user-images.githubusercontent.com/6964191/54841397-551b5b00-4cf7-11e9-868a-275c654d555c.png">

**Comment by yuviii** [comment]
However after trying for few times download succeeds. Currently i am testing in the emulator with the lollipop image.

**Comment by leomaxi** [comment]
Works now
