### ISSUE TITLE
myplanet doesnt sync deleted resources from planet from shelf

### ISSUE THREAD

**Issue by inDepthh** [open-learning-exchange/myplanet#706]

**Comment by rrijal53** [comment]
@inDepthh  We don't have any field in shelf db to check ,which resource to keep and which resource to delete from shelf db. We only have ids.   Any idea @lmmrssa  @leomaxi  ??

**Comment by leomaxi** [comment]
Now shows list already synced from resources.. If resource isn't on server, it wouldn't show up
