### ISSUE TITLE
Login : Entering the wrong user credentials twice crashing the app

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#742]
![screenshot-1555689968943](https://user-images.githubusercontent.com/6964191/56432682-0826a680-62ee-11e9-8617-3dbb08aedfc1.jpg)

**Comment by lmmrssa** [comment]
Don't see this happening on tablet running the build apk. It could be happening because you are running build copy not the apk.

**Comment by yuviii** [comment]
@lmmrssa i unistalled the previously installed app and installed from release. Sync issues might be cause but not sure.

**Comment by rrijal53** [comment]
done
