### ISSUE TITLE
Library: collection not showing when the parent collection is expanded and hidden

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#744]
![screenshot-1555690604924](https://user-images.githubusercontent.com/6964191/56433243-f2b27c00-62ef-11e9-9600-462b02e60ca8.jpg)

**Comment by rrijal53** [comment]
@yuviii  i don't found any issue . Looks like you are testing it on mobile phone , but it is working on tablet. 
![Screenshot_1556031409](https://user-images.githubusercontent.com/9145217/56591446-74fcb200-6608-11e9-9264-268e2411c4fc.png)

**Comment by leomaxi** [comment]
Resolved
