### ISSUE TITLE
Achievements: should delete reference permanently only after the update

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#745]
The reference should be invisible from view only when delete is clicked and permanently delete if the update is clicked. Currently the reference has been deleted even update is not clicked.

**Comment by rrijal53** [comment]
# have one reference
![Screenshot_1555951819](https://user-images.githubusercontent.com/9145217/56512454-24754e00-654f-11e9-8f5e-6a7fb5d74de5.png)

# deleted reference , reference is invisible
![Screenshot_1555951829](https://user-images.githubusercontent.com/9145217/56512455-24754e00-654f-11e9-8aa3-97f592487094.png)

# clicked cancel and reference is not deleted permanently
![Screenshot_1555951833](https://user-images.githubusercontent.com/9145217/56512456-24754e00-654f-11e9-925b-112d825bb289.png)

I don't see any issue here, please explain further.

**Comment by leomaxi** [comment]
Fixed
