### ISSUE TITLE
MySurveys: App getting crash when the survey is clicked

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#746]
![screenshot-1555692465117](https://user-images.githubusercontent.com/6964191/56434169-335fc480-62f3-11e9-9f45-a7ec9c4d45da.jpg)

**Comment by lmmrssa** [comment]
Can you explain how you are doing a test? I don't see any crash issues that you mentioned. Are you building apk or using the build apk?

**Comment by yuviii** [comment]
@lmmrssa I installed the apk from github release. I am not sure what is causing this crash, I tried take pending survey from my survey few times but app get crashed each time.

**Comment by rrijal53** [comment]
Have not found the issue closing it for now.
