### ISSUE TITLE
Submissions: exams is not being synced from planet

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#748]
**In Myplanet**

![screenshot-1555693567293](https://user-images.githubusercontent.com/6964191/56434754-acf8b200-62f5-11e9-9ad2-97d90b975bf5.jpg)

**in Planet**

<img width="1436" alt="Screenshot 2019-04-19 22 51 49" src="https://user-images.githubusercontent.com/6964191/56434773-c568cc80-62f5-11e9-926a-55a10e5540c6.png">

**Comment by rrijal53** [comment]
@yuviii  it only shows the pending surveys, of the logged in user. Are you testing using same login credentials in planet and myplanet???
And it is working
![Screenshot_1556032486](https://user-images.githubusercontent.com/9145217/56592650-d45bc180-660a-11e9-8401-7a6c00972488.png)

**Comment by leomaxi** [comment]
Working now
