### ISSUE TITLE
Issue with resource download

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#749]
There is resource attachment on planet.
On myplanet download status shows Finish when downloading. But it is not downloaded successfully and shows download option again and again.
On Resource view, button changes from download to open even when it is not successfully downloaded. So clicking open resources does not open resource and shows download again.

**Comment by rrijal53** [comment]
@lmmrssa  is this problem exist for specific resource ?? or for all resources? 
I don't found any issue in my case.
