### ISSUE TITLE
Course : Ask the confirmation dialog before deleting the course

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/myplanet#750]
I think it would be better to show the confirm dialog box when `Delete MyCourse` is pressed to delete the course.

For instance, sample taken from planet 

<img width="1415" alt="Screenshot 2019-04-19 23 04 29" src="https://user-images.githubusercontent.com/6964191/56435260-95222d80-62f7-11e9-8283-03110bd02b35.png">

**Comment by lmmrssa** [comment]
@yuviii Delete from MyCourse is not same as deleting course. It is Leaving course.

**Comment by lmmrssa** [comment]
@leomaxi I don't think we need this functionality. We are not deleting course. We are just removing it from his/her dashboard
