### ISSUE TITLE
open resource on course issue

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#767]
open resource button on course gives list of all resources not just from the list of course.
One of the course had only one resource on just one step. but it popup with 10-15 resources

**Comment by rrijal53** [comment]
@lmmrssa  it is working fine on my device ,, 
# When clicked open resource from detail page : 
![Screenshot_1556375165](https://user-images.githubusercontent.com/9145217/56850920-b357e100-6928-11e9-9920-2d09255e0fee.png)


# When clicked open resource from step 1
![Screenshot_1556375183](https://user-images.githubusercontent.com/9145217/56850921-b357e100-6928-11e9-9ee7-9e9ec10488d8.png)

**Comment by leomaxi** [comment]
Working fine
