### ISSUE TITLE
Sync: Upload data

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/myplanet#796]
Uploading data to server dialog should be closed if the network connection is interrupted. Currently there is no way to cancel or it keeps showing though connection goes out.

Steps to replicate:
1. start sync by pressing sync icon in top left corner of login page.
2. turn off the network connection

The dialog keeps on showing and never closes.

**Comment by leomaxi** [comment]
Wifi manipulation in app disabled
