### ISSUE TITLE
language : Arabic

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#798]
Settings and sync icon are misplaced when users switch to Arabic
<img width="747" alt="Screenshot 2019-05-10 at 3 46 24 PM" src="https://user-images.githubusercontent.com/2836302/57542466-4fc6ae00-7341-11e9-92f9-3b298830c697.png">

**Comment by lmmrssa** [comment]
Related to #801

**Comment by rrijal53** [comment]
done https://github.com/open-learning-exchange/myplanet/commit/4f7f26b88db4fbde5a6c1335e36c7d13d381b470
