### ISSUE TITLE
App crashes on startup in mobile phone 

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#820]

**Comment by leomaxi** [comment]
Crashes on this line
`switchChildMode = findViewById(R.id.switch_child_mode);
        switchChildMode.setChecked(settings.getBoolean("isChild", false));
        switchChildMode.setOnCheckedChangeListener((compoundButton, b) -> {
            settings.edit().putBoolean("isChild", b).commit();
            recreate();
        });
`
