### ISSUE TITLE
Language change Button is different in child mode and normal mode

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#847]
![Screenshot_1559316573](https://user-images.githubusercontent.com/9145217/58716629-28677c00-83e9-11e9-9409-e143eb9388e6.png)
![Screenshot_1559316579](https://user-images.githubusercontent.com/9145217/58716633-29001280-83e9-11e9-9e48-bb8e27ff6e00.png)

**Comment by lmmrssa** [comment]
@275vytran we can make 1st image to look similar to 2nd image. **Logo** **myPlanet name** **button**
