### ISSUE TITLE
Add resource on achievement is crashing app

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#851]
Crashing or making app unresponsive

**Comment by rrijal53** [comment]
@lmmrssa  working fine , need more testing.
![Screenshot_1559478652](https://user-images.githubusercontent.com/9145217/58761315-8ff50700-8562-11e9-8b9a-89c026fb0f90.png)

**Comment by rrijal53** [comment]
Issue does not exist now.
