### ISSUE TITLE
New course created with exam, survey and resource not synced

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#852]
Myplanet does not receive or show new courses created when it has exam, survey and also resource.
Might require to check if it is any specific content that is causing it or in general

**Comment by rrijal53** [comment]
@leomaxi @lmmrssa  working fine in my case,
<img width="1421" alt="Screen Shot 2019-06-01 at 20 19 16" src="https://user-images.githubusercontent.com/9145217/58749843-beafa680-84aa-11e9-9158-1ab82dd48b7e.png">

![Screenshot_1559399570](https://user-images.githubusercontent.com/9145217/58749846-c707e180-84aa-11e9-90aa-190cb5170db3.png)
![Screenshot_1559399666](https://user-images.githubusercontent.com/9145217/58749847-c707e180-84aa-11e9-8aeb-e8c8c088c54a.png)

**Comment by leomaxi** [comment]
Working
