### ISSUE TITLE
app crashes : when use internal sync menu item

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#863]
when you use internal sync menu item, app crushed
<img width="754" alt="Screenshot 2019-06-06 at 10 18 50 PM" src="https://user-images.githubusercontent.com/2836302/59070201-6234f880-88a9-11e9-9f55-6bb9f464c9bc.png">

**Comment by rrijal53** [comment]
@leomaxi  it's working in my case, need more testing in other devices .

**Comment by ibnahmadbello** [comment]
In my own case, it just log me out and asked me to login again.

**Comment by rrijal53** [comment]
issue not found
