### ISSUE TITLE
mycourse makes app non responsive

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#879]
When clicking myCourse it makes app non responsive

**Comment by inDepthh** [comment]
@lmmrssa I was unable to reproduce

**Comment by lmmrssa** [comment]
@inDepthh did you click on myCourse on menu bar?

**Comment by lmmrssa** [comment]
based on my content, it could be happening when course is deleted for course that is added in myCourse. But as that is only page where Course can be removed from myCourse, it needs to make sure that even if something record is wrong it should not crash app. We might need to check more to make sure if that is the case.
