### ISSUE TITLE
Team discussion : hide team description on small screen devices

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#886]
hide / toggle team description on small screen devices to make room for discussion
<img width="864" alt="Screenshot 2019-06-14 at 7 54 21 PM" src="https://user-images.githubusercontent.com/2836302/59534757-bd38a200-8ede-11e9-9f7f-ad89e66d979d.png">

**Comment by rrijal53** [comment]
Design is already changed  so issue doesn't exists
