### ISSUE TITLE
Message reply view

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#897]
On Message reply.
* Show old message on top so it is easier to know what reply is about.
* Add go to previous reply when there are multiple level of reply.
* Hide Add message or post message when user is on reply (not main message list)
* On team message move Add message to top bar or inside Discussion tab. It should not be visible when you are on different tab

**Comment by ChiragAwale** [comment]
@lmmrssa Would it be good to make it show in the same activity below the news like in popular social networking sites like fb, instagram etc?
