### ISSUE TITLE
Open feedback list when clicked on message icon in action bar

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#898]
Open feedback list fragment when clicking message icon in action bar , just like planet.
![Screenshot_1561130167](https://user-images.githubusercontent.com/9145217/59932923-09985a80-9468-11e9-91a4-02921dd0bdc3.png)

**Comment by ChiragAwale** [comment]
@rrijal53 Should we close this since we are using a new theme?
