### ISSUE TITLE
Surveys Under Bell Theme

### ISSUE THREAD

**Issue by jeevast** [open-learning-exchange/myplanet#900]
Survey Icon under Bell theme pulls out a blank fragment, where as in the normal theme it's pulling out the right one.

**Comment by rrijal53** [comment]
@jeevast  that survey is survey from drawer in normal theme , when we show survey list. 
Survey on dashboard is mySurvey. 
What we can do is change survey to mySurvey in dashboard , and show message "No survey" in that list fragment if list is empty.
#Syrvey list
![Screenshot_1561131826](https://user-images.githubusercontent.com/9145217/59934712-e8396d80-946b-11e9-814f-14fba0b904b7.png)
![Screenshot_1561131849](https://user-images.githubusercontent.com/9145217/59934713-e8396d80-946b-11e9-8f98-42d08bdd6de5.png)

# mySurvey
![Screenshot_1561131983](https://user-images.githubusercontent.com/9145217/59934726-eff91200-946b-11e9-829e-2b920c22530a.png)
