### ISSUE TITLE
Make 'SHOW MAIN CONVERSATION' look more like a button

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/myplanet#906]
It would look better if we put in some borders for the button. -> News -> Replies
<img width="452" alt="Screen Shot 2019-06-21 at 11 40 45 AM" src="https://user-images.githubusercontent.com/19680263/59938033-8cde8f80-9419-11e9-88e7-8f0a42b09f04.png">

**Comment by rrijal53** [comment]
related to https://github.com/open-learning-exchange/myplanet/pull/909

**Comment by rrijal53** [comment]
closing this issue, covered in #909
