### ISSUE TITLE
add README and description

### ISSUE THREAD

**Issue by xyb994** [open-learning-exchange/myplanet#92]

**Comment by aakarnik** [comment]
More images:
[mac](https://user-images.githubusercontent.com/37878201/43735982-1d0cf1c2-998a-11e8-8edb-5bfea2522a35.png)
[windows](https://user-images.githubusercontent.com/37878201/43735983-1d1ebbd2-998a-11e8-9579-4124f6c41086.JPG)

**Comment by leomaxi** [comment]
Updated but needs more ideas..
