### ISSUE TITLE
Texts hidden in dashboard 

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/myplanet#968]
MyLife MyCourse MyLibrary
<img width="455" alt="Screen Shot 2019-07-10 at 10 20 27 AM" src="https://user-images.githubusercontent.com/19680263/60981644-5ac79b80-a2fc-11e9-9130-9f8804fbb079.png">

**Comment by raisinman99** [comment]
It shows up fine for me.

**Comment by raisinman99** [comment]
It shows up fine for me

**Comment by ChiragAwale** [comment]
@raisinman99 Would you be able to check if you have the latest version of master in? Thank you.

**Comment by raisinman99** [comment]
yes you were right it was not latest version
