### ISSUE TITLE
myLife fragment buttons

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#992]
Padding between text and edge is too close. Items that already exist in myLife must be "Remove" from myLife
<img width="770" alt="Screenshot 2019-07-16 at 9 43 49 AM" src="https://user-images.githubusercontent.com/2836302/61284612-d6b75d00-a7ae-11e9-84d0-8d5e41788a2c.png">

**Comment by ChiragAwale** [comment]
@leomaxi I have created a PR that will fix the padding issues, but I think its better to create a separate issue for "Remove" feature since we need to implement a dynamic myLife bar on the dashboard as well.

**Comment by ChiragAwale** [comment]
#996 
I can close it if not required.
