### ISSUE TITLE
Course security by photo capturing

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#994]
Take a photo silently on device and save on device when . user opens a course / moves to next step

**Comment by ChiragAwale** [comment]
I feel like there will be a privacy issue with it. Is this only when taking exams in supervised environments? or any time during home?

**Comment by raisinman99** [comment]
I agree with Chirag. This may be a privacy violation when taking a pic without their knowledge.

**Comment by leomaxi** [comment]
There will be a disclaimer. On courses that require taking photos to authenticate person / persons taking the course.  When implemented as a beta feature, courses with this requirement will let users agree to T&C before they proceed. If they don't agree,they can't take that specific course.. but can take other courses ...

**Comment by ChiragAwale** [comment]
Gotcha!

**Comment by raisinman99** [comment]
Make sense!

**Comment by rrijal53** [comment]
@leomaxi @ChiragAwale   is is already done. When we click finish button after taking course, app will capture image. Which is stored in ole/userimages.

**Comment by ChiragAwale** [comment]
@rrijal53 Got it.
